<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administrador Remates</name>
   <tag></tag>
   <elementGuidId>50544ed3-ca1a-4655-9cc9-93d1ed6e98b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MP_ADMREM-itemEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MP_ADMREM-itemEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4487eb2-e5a7-49d3-8ea1-ae9bef8b61dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MP_ADMREM-itemEl</value>
      <webElementGuid>8ac6644a-27f1-491e-bb91-39658a893f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>itemEl</value>
      <webElementGuid>980280ae-708d-4804-82b9-ba38ee612ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-link x-focus x-menu-item-focus x-menu-item-default-focus</value>
      <webElementGuid>d463b48b-2d8f-470d-80e4-f434596dc6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0ad780e3-774f-4906-9e84-7ba8f2828e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>dadaf8ec-2403-44b1-b1a8-d55e48dc6444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e73dfb3-cd52-40e1-8348-3145eff96737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c57907e7-3031-416a-8c22-d087d4b36573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dfd7f41a-2c0e-4e0e-8dd9-6498bbc45f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>MP_ADMREM</value>
      <webElementGuid>f5a96d15-0fab-4406-838c-b238b9dfee2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrador Remates</value>
      <webElementGuid>7207fa42-4932-451b-90ac-d8974ffa6ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MP_ADMREM-itemEl&quot;)</value>
      <webElementGuid>d242b2d0-c59f-41a5-a9a8-2e33c69e3f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MP_ADMREM-itemEl']</value>
      <webElementGuid>a06fdbfc-8964-484d-845f-0fd3e86ef2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MP_ADMREM']/a</value>
      <webElementGuid>93103df1-d2b3-4da3-b411-a2d1ad6c6c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jmonardes, Jose Emilio Monardes Godoy'])[1]/following::a[1]</value>
      <webElementGuid>643e4fb2-ee9a-4d1d-a516-ddb96fd39cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cascada Windows'])[1]/following::a[1]</value>
      <webElementGuid>6220207d-a214-4ea2-b19a-59ab9ee90709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrador'])[2]/preceding::a[1]</value>
      <webElementGuid>2e135eec-89b8-4829-b8b7-b17aaa32411a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>122e9e25-eb81-4c9b-9023-e08540cf7b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/a</value>
      <webElementGuid>ba986bc9-e70b-4413-ad49-cbfe1b5a1ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MP_ADMREM-itemEl' and @href = '#' and (text() = 'Administrador Remates' or . = 'Administrador Remates')]</value>
      <webElementGuid>adadbb54-32dd-44a7-9170-e6dc2c19a642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
