<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Agregar</name>
   <tag></tag>
   <elementGuidId>9923ffa2-2645-47a4-b32c-3ee58f7b4b59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnNuevo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnNuevo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26595b9d-6f06-4fd6-b009-7d5eed934250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn x-unselectable x-box-item x-toolbar-item x-btn-primary-small x-btn-over x-focus x-btn-focus x-btn-primary-small-focus</value>
      <webElementGuid>d9daa53e-8c0a-4f95-9e7a-32a4792c1fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d55d5782-4fa7-4826-b800-840c334a8262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2b3b9008-4005-4731-bfdc-5f3c775536a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnNuevo</value>
      <webElementGuid>af8da6e4-3afc-4528-9338-dee3806cb42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9fa5119f-4ca0-4961-860c-90781d690512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qtip</name>
      <type>Main</type>
      <value>Agregar un nuevo registro</value>
      <webElementGuid>e1659ac0-15fd-43a3-8755-8f1495a50e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>btnNuevo</value>
      <webElementGuid>f4a0a247-6e4d-4e83-b589-2b2bdbb07452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Agregar</value>
      <webElementGuid>8b96131f-ea1b-40b5-b5f8-4bfdf3d82adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnNuevo&quot;)</value>
      <webElementGuid>9c2b1910-a980-4e45-9101-a3d3c6d24b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_NMREM_IFrame</value>
      <webElementGuid>169ba962-48d3-4ae1-a1e8-da2079e100a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnNuevo']</value>
      <webElementGuid>c8b62da4-eba7-4930-bb8e-f3463b9f6c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tb_grilla-targetEl']/a</value>
      <webElementGuid>a399e93a-85e8-409d-9d0f-16dc31894006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar'])[1]/preceding::a[1]</value>
      <webElementGuid>e310131f-f213-4d6b-b3d7-09a2885ffe1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>cdc797bb-a421-4388-ba37-4317a17dcbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnNuevo' and (text() = ' Agregar' or . = ' Agregar')]</value>
      <webElementGuid>4355dd90-2771-4ecd-aa6f-d8e4383736bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
