<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Editar Lote (1)</name>
   <tag></tag>
   <elementGuidId>63aff457-459a-406a-81f6-f14aa731f366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuitem-1132-itemEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuitem-1132-itemEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c9cd1ff3-9ddf-4feb-acfb-da7a359cabb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuitem-1132-itemEl</value>
      <webElementGuid>f055b122-0654-4a9e-b6c3-1c8dc5e67eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>itemEl</value>
      <webElementGuid>a06930f9-8b1b-437c-b296-59f9d1566181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-link x-focus x-menu-item-focus x-menu-item-default-focus</value>
      <webElementGuid>01c0ae79-20c0-42c2-887a-d6632edc2fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ac337351-8072-4a1f-b481-7e4af9ee3186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>dbfc4bf0-4fa8-41d7-b3eb-099f07903bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4f90d0d4-3f3c-4c70-b1ab-6de88756fb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>879bdbf1-9e62-4b31-9158-8cdd4e264819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f04eec77-aa1a-47f8-b00c-4e8630a8d9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>menuitem-1132</value>
      <webElementGuid>98bd1886-91a5-4f04-87fb-58f8bbb9266d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar Lote</value>
      <webElementGuid>c6207da7-a43f-47c9-9f14-4a0afc5df9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuitem-1132-itemEl&quot;)</value>
      <webElementGuid>102139dc-3ae2-4dfc-b674-afd62f331c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2548_IFrame</value>
      <webElementGuid>ac79e0a0-7d42-4378-8c44-47e2e538c1cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menuitem-1132-itemEl']</value>
      <webElementGuid>f63434ba-f15c-49b7-a578-7cdcba3973d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuitem-1132']/a</value>
      <webElementGuid>0bc4a3c6-aab3-4cf3-bd6f-1a9a2adfa432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu de Opciones del Lote'])[1]/following::a[1]</value>
      <webElementGuid>9a2c0386-5368-46fb-84ec-57324391ff5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imágenes Lote'])[1]/preceding::a[1]</value>
      <webElementGuid>6663232c-343c-43f4-bee2-99102d5af12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>b7b36994-c98e-49e8-aca7-d8cf25e0e6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>44974c44-03a0-401f-bcc6-2979d0989c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menuitem-1132-itemEl' and @href = '#' and (text() = 'Editar Lote' or . = 'Editar Lote')]</value>
      <webElementGuid>013728fa-653c-42b9-bb30-3fe0556a38bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
