<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lotes Remate (1)</name>
   <tag></tag>
   <elementGuidId>e40341b1-4579-406c-8d49-c6e7880e1120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuitem-1124-itemEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menuitem-1124-itemEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>05c208e5-0ac9-4a5f-8485-fc69aca18a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuitem-1124-itemEl</value>
      <webElementGuid>a9538b2c-de25-4c76-a470-4e24bd3477c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>itemEl</value>
      <webElementGuid>7115e86f-8ba1-4dcb-a3e4-643761d3d232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-link x-focus x-menu-item-focus x-menu-item-default-focus</value>
      <webElementGuid>df147c7c-3931-4ad2-b9d7-d69b26965f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b76837b3-c89b-496d-b8db-13c45d18696b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>5a6ba630-09d5-441e-a658-42cb16f98642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>128aab02-97b2-4f37-a4e4-c10a06184551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8950811e-37ef-4587-b438-f0a22be8d6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>068ca871-fa2f-41fc-8c9e-d7abc022b90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>menuitem-1124</value>
      <webElementGuid>a0f83fd9-a00b-431e-9204-e8f131785de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lotes Remate</value>
      <webElementGuid>82dd989c-57f4-4a09-aace-816d7bfff4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuitem-1124-itemEl&quot;)</value>
      <webElementGuid>45ba43d0-6c2a-46eb-b30f-bb8bbe0b1863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_NMREM_IFrame_1</value>
      <webElementGuid>a592bb20-7af6-48da-ac9d-8bc7c3cd76cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menuitem-1124-itemEl']</value>
      <webElementGuid>8445f8e1-1317-41a2-854a-79ed1cb8268d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menuitem-1124']/a</value>
      <webElementGuid>4cdeb186-cc80-4f83-9f38-42afad3d6d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imágenes Remate'])[1]/following::a[1]</value>
      <webElementGuid>9f97f802-2dd9-4622-b6d2-6995d1c53355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar Remate'])[1]/following::a[2]</value>
      <webElementGuid>8232d7e7-cefa-400d-b64e-785cc1eeb5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar Catálogo'])[1]/preceding::a[1]</value>
      <webElementGuid>31505658-372d-47d6-8e6f-ae728be291aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>5f2aa152-1f77-4d0d-b696-0906ad42939b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>3d435014-2320-4178-9d70-ae93c405e267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menuitem-1124-itemEl' and @href = '#' and (text() = 'Lotes Remate' or . = 'Lotes Remate')]</value>
      <webElementGuid>785ce2a7-7c97-4693-9f01-e94facf30b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
