<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nmina Remates</name>
   <tag></tag>
   <elementGuidId>8f918ddf-6e40-4123-98d7-2fa23e9b976f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MH_NÓMREM-itemEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='MH_NÓMREM-itemEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d616961-7eb4-48f6-8498-5afdf4dbf7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH_NÓMREM-itemEl</value>
      <webElementGuid>ce2e3958-79b5-4b5f-bfe7-8d17a8b33878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>itemEl</value>
      <webElementGuid>c20926e2-f1f1-4f19-88ca-deba10806730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-link x-focus x-menu-item-focus x-menu-item-default-focus</value>
      <webElementGuid>fe964580-a6b6-4972-9aa9-620673e7ac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c799e339-386c-41d4-aec6-4412421c5a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f594beba-a41c-4e53-abe3-83ebc067d073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8074c5fe-9855-477e-afc8-07a0adb55533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>70a1a856-e3b2-4ca5-8ac8-829363047b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e63b7fa-eb8d-4b87-a2ac-f02f4bc956da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>MH_NÓMREM</value>
      <webElementGuid>2e3f0795-8317-42e2-810c-4100cadef36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nómina Remates</value>
      <webElementGuid>2be61c2f-ac4f-4ae2-b3e3-708c0a10290d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH_NÓMREM-itemEl&quot;)</value>
      <webElementGuid>671fd5a6-7ca7-41a4-8430-8ba4790d1671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='MH_NÓMREM-itemEl']</value>
      <webElementGuid>bbecfa8b-f58e-46cc-8824-5b3f85c0d40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MH_NÓMREM']/a</value>
      <webElementGuid>cfdb823d-381d-480c-b2ba-97e934eb7d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/following::a[1]</value>
      <webElementGuid>1a245722-5608-4187-885d-6d898976a358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerca de'])[1]/following::a[2]</value>
      <webElementGuid>271abf5f-ac82-4493-b809-85d5b34c962d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandantes'])[1]/preceding::a[1]</value>
      <webElementGuid>0883201b-86e6-45a7-a4ff-699e8b33abf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>4a8dbf15-a651-4eb0-b2a8-40e978750cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[3]/div/div/a</value>
      <webElementGuid>ea8c8850-fa94-4323-850d-a8c4c2e34754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'MH_NÓMREM-itemEl' and @href = '#' and (text() = 'Nómina Remates' or . = 'Nómina Remates')]</value>
      <webElementGuid>a99d6d1f-a914-4672-8310-f6b516984e4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
