<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Opciones</name>
   <tag></tag>
   <elementGuidId>96f45434-2dba-45c2-8f99-adb4cff06cfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1130</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button-1130']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7dd5046f-e37d-4a9c-87db-cb51c84f3752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn x-unselectable x-box-item x-toolbar-item x-btn-default-toolbar-small x-btn-over</value>
      <webElementGuid>bf299421-1ee6-4884-b2d1-321f1b87294a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidefocus</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>873e66b8-3fd1-462d-80d1-b8b516dd94bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f68bc064-83fb-4dd5-8126-16d5632302a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1130</value>
      <webElementGuid>894d73df-b012-43ca-aa4e-0956af49d4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f0871eab-0bbe-4c76-bf2d-aa418a3260b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Opciones</value>
      <webElementGuid>1a7462ec-5cd1-4c56-864f-1087c591de78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1130&quot;)</value>
      <webElementGuid>d26ad8fc-0489-460b-8a45-401b7b622e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2555_IFrame_1</value>
      <webElementGuid>21e4c3fe-db48-4417-9f45-4d3fe4a981b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button-1130']</value>
      <webElementGuid>fe2c455f-993c-45d7-8838-a300e06eb854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolbar-1129-targetEl']/a</value>
      <webElementGuid>49add4a3-4c80-49a7-ae25-53384e209945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[2]/following::a[1]</value>
      <webElementGuid>3a60c1af-22bf-4659-bbf3-7d76c2289482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Lote'])[1]/following::a[1]</value>
      <webElementGuid>bad83357-22f5-4180-b650-cf84ae6cd219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOTE 1'])[1]/preceding::a[1]</value>
      <webElementGuid>b1f6a61d-0c1b-4b2f-971b-8b9ec514b8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a</value>
      <webElementGuid>e2156b34-f745-4e41-aab4-e145b864a026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'button-1130' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>2b664907-05bd-45a7-88b7-c3819e263d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
