<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inicio_tbseparator-1018</name>
   <tag></tag>
   <elementGuidId>42bb83fa-2554-4303-9181-3a2dd142af9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tbseparator-1018</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbseparator-1018']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ddb25c3-1356-4356-bb4d-74a0e242d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-toolbar-separator x-toolbar-separator-horizontal x-box-item x-toolbar-item</value>
      <webElementGuid>d1a27cbe-c550-4aa3-9c17-9e880b4a30a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbseparator-1018</value>
      <webElementGuid>bc46e603-48bd-4921-9e39-b4448d8de99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbseparator-1018&quot;)</value>
      <webElementGuid>f5e71a29-4ff9-4dbd-997a-75b08213d475</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tbseparator-1018']</value>
      <webElementGuid>3e23b289-d74c-4b9f-98dd-d5418af9eeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl16-targetEl']/div</value>
      <webElementGuid>5712006d-1d77-4610-8c57-ad7e6c68d120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>9414fa50-b598-427f-a01b-dd8ab7709507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tbseparator-1018']</value>
      <webElementGuid>817c66c0-d937-4cc0-9c77-c7fc8c90b125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
