<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__txtFechaRemate-trigger-picker</name>
   <tag></tag>
   <elementGuidId>40a55baa-2bd3-4892-9c63-ad83a7295d7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='txtFechaRemate-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtFechaRemate-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b69a171a-1393-4eb2-bf1a-3ee70823ae09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFechaRemate-trigger-picker</value>
      <webElementGuid>c73bd780-f352-4cd2-b9af-e470c9e7a9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-date-trigger x-form-date-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>ae55a437-2bb7-41dd-bff4-d03e6afac041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFechaRemate-trigger-picker&quot;)</value>
      <webElementGuid>a626a26d-4fdc-4bba-98c6-752be3960dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>b6d82f23-a83b-4679-a251-663c9f799172</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='txtFechaRemate-trigger-picker']</value>
      <webElementGuid>8e20c66a-9aa2-4453-90e0-a045abbdbf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='txtFechaRemate-triggerWrap']/div[2]</value>
      <webElementGuid>5940fc96-57ef-4dbd-afc9-00dfc21f9210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>defeeff7-cc5b-4145-902d-45178b7123e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'txtFechaRemate-trigger-picker']</value>
      <webElementGuid>2b9b25e1-bdb5-4ffa-95e4-05cb21d40bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
