<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Proceso terminado</name>
   <tag></tag>
   <elementGuidId>288c6e2c-a568-4189-8e7a-b2567a08cf40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title-1035-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title-1035-textEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a1c5557-0c16-4865-88ab-85241663933f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title-1035-textEl</value>
      <webElementGuid>b0d34bc9-7f0b-4c76-bd12-f95e60bc622e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>d4acdc42-7ded-4fa2-9b7e-c01d4ba60e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-title-text x-title-text-default x-title-item</value>
      <webElementGuid>a07fd970-0422-42ae-a65c-bcf40eb718ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>7cdeece0-ec89-4081-bd00-caf4180efff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceso terminado</value>
      <webElementGuid>f0bab151-9116-494f-86ec-8fa747bf8a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-1035-textEl&quot;)</value>
      <webElementGuid>389b68ca-b82e-49d1-a4b4-5f719f33e25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Carga Masiva_ext-element-57</value>
      <webElementGuid>33afe2a4-3c77-4ecc-8722-9f223415cd91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='title-1035-textEl']</value>
      <webElementGuid>c5c456cd-c96f-4ec7-a088-48c4eca480bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-1035']/div</value>
      <webElementGuid>3017bc60-7d6a-4c26-a480-efd466226280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planilla Excel'])[1]/following::div[26]</value>
      <webElementGuid>cac8966d-3001-493c-adfd-bd6d15bf3463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lotes cargado exitosamente.'])[1]/preceding::div[3]</value>
      <webElementGuid>02fbbb2d-2583-487b-88f1-4f4685e1bf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::div[30]</value>
      <webElementGuid>b5ede311-f050-4c64-b883-c3f911229b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceso terminado']/parent::*</value>
      <webElementGuid>3c72ab56-cb5c-47a0-a466-d377d257fc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>44495b55-e47e-4612-b7e5-0c24e04ec951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'title-1035-textEl' and (text() = 'Proceso terminado' or . = 'Proceso terminado')]</value>
      <webElementGuid>3eb32f2a-1d4d-42dc-a95a-98468d047bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
