<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Transferencia</name>
   <tag></tag>
   <elementGuidId>42672c74-ae44-4e69-854e-513bf149e97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='boundlist-1144-listEl']/li[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.x-combo-list-item.x-mcombo-item-unchecked</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6af0c919-e94a-4f7d-8297-07807384be03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-combo-list-item x-mcombo-item-unchecked</value>
      <webElementGuid>543d9976-e9ea-4a64-b8b4-d2b22e5f8a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia</value>
      <webElementGuid>c61dfff7-4cb3-4426-a4a9-156e3f1cb9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boundlist-1144-listEl&quot;)/li[@class=&quot;x-boundlist-item x-boundlist-item-over&quot;]/div[@class=&quot;x-combo-list-item x-mcombo-item-unchecked&quot;]</value>
      <webElementGuid>318638c3-94b4-4de4-85cc-dc9ef3895b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>1b991329-0078-4b4d-b407-f3caf13835ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='boundlist-1144-listEl']/li[3]/div</value>
      <webElementGuid>c0e4bad8-a84a-4c37-a8f1-eecd4002d2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Getnet'])[1]/following::div[1]</value>
      <webElementGuid>aaaa6ebd-8303-4b20-a608-758ee6dab202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linkify'])[1]/following::div[3]</value>
      <webElementGuid>439904e7-8c86-42b5-923f-f036b4e5258a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div</value>
      <webElementGuid>9fb8ea1e-2ea8-4513-99e6-24a442ecc5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Transferencia' or . = 'Transferencia')]</value>
      <webElementGuid>259f65ce-a80f-420d-a8ba-b8b789c30f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='boundlist-1151-listEl']/li[3]/div</value>
      <webElementGuid>12a5d0cc-e853-4fdc-a325-db3a9d751020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
