<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__cmbTipoDireccion-trigger-picker</name>
   <tag></tag>
   <elementGuidId>1863c787-afb0-4a2c-be31-caff954beb04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmbTipoDireccion-trigger-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='cmbTipoDireccion-labelEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77166181-eccd-4c98-a8a5-bd2fe8514f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmbTipoDireccion-trigger-picker</value>
      <webElementGuid>b3e6e221-4758-49f2-9afd-7df7b380bc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>35ccc1cf-c4b5-4dc8-b27a-8979fc324bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmbTipoDireccion-trigger-picker&quot;)</value>
      <webElementGuid>59f97f07-26f8-455c-adba-30528e4c36df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>4a9ec679-c058-4096-9568-4cd58c26ebb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cmbTipoDireccion-trigger-picker']</value>
      <webElementGuid>c8cbfd47-61f0-49f3-a415-a0dc3316c848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmbTipoDireccion-triggerWrap']/div[2]</value>
      <webElementGuid>ba1b72c4-3070-4fe7-800b-a90b674b33eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>4de4a326-a680-4671-9331-31ff12ac10e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cmbTipoDireccion-trigger-picker']</value>
      <webElementGuid>bfa9fbd1-25af-4a6b-901d-1f26498d8d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
