<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Opciones_gridview-1104</name>
   <tag></tag>
   <elementGuidId>775c76a5-c368-41d9-a427-a351136b12c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridview-1104</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gridview-1104']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>93bb46bf-1129-4025-9112-a9ac0b1695dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-grid-view x-grid-with-row-lines x-fit-item x-grid-view-default x-unselectable x-focus x-grid-view-focus x-grid-view-default-focus</value>
      <webElementGuid>db644675-7006-440f-a761-6df5ec99ddc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridview-1104</value>
      <webElementGuid>761cd95c-1d5c-4158-9bd6-b22ef2442aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>36824622-43d3-46a5-8c02-48a12b3a9223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>gridview-1104</value>
      <webElementGuid>908c37dc-42db-41a0-aef0-62355f4561ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridview-1104&quot;)</value>
      <webElementGuid>c6f897c4-442d-4ab0-acaf-09d805046187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2555_IFrame</value>
      <webElementGuid>22b6eea4-f814-442a-98a2-84543602aa76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='gridview-1104']</value>
      <webElementGuid>08992eb4-c667-4f00-80c6-04eb165d47fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gd_grilla-body']/div</value>
      <webElementGuid>1af43c95-3bdf-4334-b6ea-e97c2bcde515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[2]/following::div[2]</value>
      <webElementGuid>0a432352-b50c-46f2-a828-2f769af44660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Lote'])[1]/following::div[17]</value>
      <webElementGuid>0bc45f6a-28a6-4695-8a57-7d96d341d8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargando...'])[1]/preceding::div[3]</value>
      <webElementGuid>bbfe4ba5-ddf6-42e1-b538-d20e76241bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Página'])[1]/preceding::div[8]</value>
      <webElementGuid>94149483-f027-4e1e-8ac4-c9ec56fccbb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>29bdb8e3-bf59-4412-9499-f4dd71999d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'gridview-1104']</value>
      <webElementGuid>f1751737-2f85-4058-9bd3-0602fb503724</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
