<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__cmbTipoPago-trigger-picker</name>
   <tag></tag>
   <elementGuidId>18935fdf-90fe-4213-b45b-98f35b90e1dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmbTipoPago-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cmbTipoPago-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>392c6453-918d-4af9-a87f-0d582d332fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmbTipoPago-trigger-picker</value>
      <webElementGuid>dfff96f9-2d3e-46a7-90a2-92f6b625374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>23d36d5d-8cf6-4914-b9dc-7edd927b3ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmbTipoPago-trigger-picker&quot;)</value>
      <webElementGuid>31d8fe2e-bd63-49d4-94c6-6538b2d2e849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>7ab13559-bdbe-4879-9160-6d1cc01a2d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cmbTipoPago-trigger-picker']</value>
      <webElementGuid>0d1bd1da-1399-4fc3-8015-b99ac2568fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmbTipoPago-triggerWrap']/div[2]</value>
      <webElementGuid>2f20d5a9-b809-4580-8b1e-bf66edf52b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f5e2f320-88cf-419f-b12d-17fab92877e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cmbTipoPago-trigger-picker']</value>
      <webElementGuid>c55a6f86-36f5-4826-b4f0-f4fb81269e2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
