<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_El registro ha sido modificado correctamente (1)</name>
   <tag></tag>
   <elementGuidId>62c8790e-4b9c-4383-944c-477553d47e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#container-1004-innerCt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-1004-innerCt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2232b648-1a86-48b9-affb-e8255c916aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container-1004-innerCt</value>
      <webElementGuid>51b48e60-0b29-4255-99c3-e6f07f9b75e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>ef3eff48-d3c6-408c-b343-439e09d6c6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7412735a-765f-47f9-a517-bf01517f65dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>f57faf41-dbcc-4954-b8bf-4ce73362d706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El registro ha sido modificado correctamente.</value>
      <webElementGuid>8a3e0be5-266f-4039-b8c5-a1f2e4051828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-1004-innerCt&quot;)</value>
      <webElementGuid>a4715a13-5dac-4363-b933-5bf7365ab3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>ddd4d896-c070-4647-86fb-4fa99c2d5059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='container-1004-innerCt']</value>
      <webElementGuid>e6ed1405-4f68-4741-8717-d948ac6e791b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-1004']/div</value>
      <webElementGuid>d5218a47-ce3c-4351-a932-771ac8182dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::div[6]</value>
      <webElementGuid>4ba25d8b-a618-4876-ac49-57a45fb20733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::div[24]</value>
      <webElementGuid>7e9a2042-faef-43e1-aa03-a83ebc10a239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div</value>
      <webElementGuid>541e6bc7-356c-4f93-8855-bbdd96c7a30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container-1004-innerCt' and (text() = 'El registro ha sido modificado correctamente.' or . = 'El registro ha sido modificado correctamente.')]</value>
      <webElementGuid>e96b2efe-d076-45b8-b099-a4fd303ac958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
