<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inicio de SesinNombre UsuarioPasswordSu_cea2ea</name>
   <tag></tag>
   <elementGuidId>24916a2d-103a-4341-833a-2716f6b41f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Viewport1-innerCt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Viewport1-innerCt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7de639c-a698-4a47-8c2b-220c890a0664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Viewport1-innerCt</value>
      <webElementGuid>5a9f9357-126d-4db0-8db5-59d6dc8f516c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>de93dfe6-32ee-4e1a-bee9-97a25b8ba554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>78190a9a-15fe-42e1-96c7-0bc96a8916ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>40cab6ff-30fe-4b64-9e32-b8eddfa2c80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inicio de SesiónNombre Usuario:Password:Su Clave es Requedida.Perfil:¿Olvidaste tu contraseña? LoginVersión 3.0.2.2Este sitio esta Optimizado para Google Chrome y Mozilla Firefox</value>
      <webElementGuid>4c36db8b-b5bc-4322-a082-8fc2985de52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Viewport1-innerCt&quot;)</value>
      <webElementGuid>3e86caac-2151-40fd-ba2c-f7088f860d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='Viewport1-innerCt']</value>
      <webElementGuid>53069a5a-d3bd-436e-b2d6-3819598f07f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div</value>
      <webElementGuid>cd3cd21e-21b0-4d79-a378-0fec54e6d697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>88a32659-5fe2-4136-94db-625840d94d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'Viewport1-innerCt' and (text() = ' Inicio de SesiónNombre Usuario:Password:Su Clave es Requedida.Perfil:¿Olvidaste tu contraseña? LoginVersión 3.0.2.2Este sitio esta Optimizado para Google Chrome y Mozilla Firefox' or . = ' Inicio de SesiónNombre Usuario:Password:Su Clave es Requedida.Perfil:¿Olvidaste tu contraseña? LoginVersión 3.0.2.2Este sitio esta Optimizado para Google Chrome y Mozilla Firefox')]</value>
      <webElementGuid>46750031-8294-4f28-8b43-09c7e3c60c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
