<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cargar Excel</name>
   <tag></tag>
   <elementGuidId>e5240110-387e-446e-9156-2a2ca3630c21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fileExcel-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fileExcel-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0143f49e-a70d-4570-958c-50f86733162a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn x-form-file-btn x-unselectable x-btn-default-small x-btn-over x-focus x-btn-focus x-btn-default-small-focus</value>
      <webElementGuid>cf146306-fa80-4420-b7b2-e87ca23ff19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>de16307f-fdfc-42e5-9c04-68709faa4059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileExcel-button</value>
      <webElementGuid>5892f326-f8b2-4fc1-84bb-29ba76c78721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cargar Excel</value>
      <webElementGuid>c7b58526-9662-413a-ae37-23e615a35489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileExcel-button&quot;)</value>
      <webElementGuid>f876619e-1530-45d9-a830-6b6429be263e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>c1d90891-78dc-4033-9305-8bd0f19462cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='fileExcel-button']</value>
      <webElementGuid>03ec312d-e78e-477a-bd7b-d7c755ea0ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fileExcel-trigger-filebutton']/div</value>
      <webElementGuid>174a042b-5f2e-40ad-aa72-b4b406b86f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carga de Imagenes'])[1]/following::div[18]</value>
      <webElementGuid>d674b9d9-5739-420e-bb1b-8495f87f957b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imágenes'])[2]/following::div[18]</value>
      <webElementGuid>d570a0e7-d6c7-4344-be39-60e888e5ca28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limpiar'])[1]/preceding::div[3]</value>
      <webElementGuid>64dc6c3b-adfc-4659-8dc6-4eb8242b3134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>6bd767e9-f77c-4038-b377-b99400bb120f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'fileExcel-button' and (text() = ' Cargar Excel' or . = ' Cargar Excel')]</value>
      <webElementGuid>fc1da8b7-9759-4eef-b319-feb4b3d35b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
