<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Informe de Imagenes y Videos</name>
   <tag></tag>
   <elementGuidId>bb7e88ca-c22a-434c-ae26-c6aa48192a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title-1042-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='title-1042-textEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>608ad7f0-8e61-4972-9f9d-cf6f828881bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title-1042-textEl</value>
      <webElementGuid>f6f44fea-6e69-4389-8931-30c0f88df214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>c5e23f50-6c8c-4933-a0b0-89b7d5120680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-title-text x-title-text-default x-title-item</value>
      <webElementGuid>b104d6c5-710e-4f77-9c67-eff0cb09c2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>906c3aa6-0777-464f-ac82-cea0bf5dd21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Informe de Imagenes y Videos</value>
      <webElementGuid>609c6e86-9bdf-4a6b-974c-b2ae21ae707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-1042-textEl&quot;)</value>
      <webElementGuid>71770f08-01f7-44ca-b6fe-bf12abebad49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='title-1042-textEl']</value>
      <webElementGuid>5dfab677-5cc0-44b2-b3af-e60f89ad2d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='title-1042']/div[2]</value>
      <webElementGuid>4626a791-094d-45c7-baef-41930609276b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nómina Remates'])[4]/following::div[16]</value>
      <webElementGuid>dc3bd250-c1e3-4169-ad7b-5104194c21ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nómina Remates'])[3]/following::div[36]</value>
      <webElementGuid>b0259cfb-396a-4419-bf66-5906a127c9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informe de Imagenes y Videos'])[2]/preceding::div[15]</value>
      <webElementGuid>3ea2fa7f-5b14-4157-80cf-fe0cf8ab6ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Informe de Imagenes y Videos']/parent::*</value>
      <webElementGuid>fcb9a7e0-1ee5-48b0-85a8-a688bc0b8610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div/div[2]</value>
      <webElementGuid>ffa92a66-0b54-4075-b4b2-54379acb5dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'title-1042-textEl' and (text() = 'Informe de Imagenes y Videos' or . = 'Informe de Imagenes y Videos')]</value>
      <webElementGuid>7e1fd814-a24d-44cf-bd37-75bcb3635488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
