<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_InicioTtulo WindowCascada WindowPERFILES1525</name>
   <tag></tag>
   <elementGuidId>76de798a-418b-4a40-85aa-e4794b08c337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl16-innerCt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl16-innerCt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>daa39e20-fdae-4230-9a11-e3bd792cb864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl16-innerCt</value>
      <webElementGuid>b4b4a6a9-cbcd-4170-8c23-db269108453f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>68821842-7435-4cb1-915c-3b2b98879094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>fd6d879e-a3da-4366-a13f-52e80156b775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>73257063-85e0-4075-8169-bf9a6569a759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inicio Título Window Cascada Window  PERFILES15:25</value>
      <webElementGuid>566d9b36-0dca-4a45-acbb-32f7c05da665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl16-innerCt&quot;)</value>
      <webElementGuid>e8273452-4338-427a-82cc-44f901c9bc2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl16-innerCt']</value>
      <webElementGuid>075977c6-8b88-481c-b798-1e230bd3f0fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl16']/div</value>
      <webElementGuid>7ca98610-2102-4c4e-96eb-2dc3981325a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>6b55defd-11c5-4c0c-8b56-550f65c18ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl16-innerCt' and (text() = ' Inicio Título Window Cascada Window  PERFILES15:25' or . = ' Inicio Título Window Cascada Window  PERFILES15:25')]</value>
      <webElementGuid>522d0000-6187-4141-8fb4-fd285180b3bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
