<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__cmbSubCategoria-trigger-picker</name>
   <tag></tag>
   <elementGuidId>90868343-9dd3-4e29-bc17-24d52a5b847b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cmbSubCategoria-trigger-picker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmbSubCategoria-trigger-picker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8123c563-4454-4322-9e00-545154c320d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmbSubCategoria-trigger-picker</value>
      <webElementGuid>2a768b2e-f765-47e3-a82c-738c9cddf438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>f1fd6450-5e8e-4701-a39d-16aaf2fde496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmbSubCategoria-trigger-picker&quot;)</value>
      <webElementGuid>b125d7e8-2e61-46b3-a921-dce09b07fa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>d8145eaa-e1fb-4347-8d94-a86403c48000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cmbSubCategoria-trigger-picker']</value>
      <webElementGuid>cc4fed1f-d14e-42a8-b299-8f4ce2edbb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmbSubCategoria-triggerWrap']/div[2]</value>
      <webElementGuid>69e0f4ce-fed0-433b-9823-28c3fb597f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div[3]/div/div/div[2]</value>
      <webElementGuid>078f7bca-aaa1-40c2-b9ab-e9c89e5cbfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cmbSubCategoria-trigger-picker']</value>
      <webElementGuid>c9f04ea7-83cc-4067-8589-0d9ec41b3dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
