<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__cmbFamilias-trigger-picker</name>
   <tag></tag>
   <elementGuidId>058cc2d7-3bb2-4a77-a8ce-bfdeba30a021</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmbFamilias-trigger-picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cmbFamilias-trigger-picker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>043368cc-29cf-4bc9-a238-7e865ddcbec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmbFamilias-trigger-picker</value>
      <webElementGuid>187f396d-4625-4e45-805b-6a508cb6dbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-trigger x-form-trigger-default x-form-arrow-trigger x-form-arrow-trigger-default  x-form-trigger-over x-form-trigger-focus</value>
      <webElementGuid>d3ae6ad3-6c5b-4e81-a61d-ee32e5a1b9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmbFamilias-trigger-picker&quot;)</value>
      <webElementGuid>8e667892-8a2d-46ca-9d32-14e64338fe20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>ea720f95-189e-427f-8f7f-04a40b7cf221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cmbFamilias-trigger-picker']</value>
      <webElementGuid>784a622f-3d4e-4c53-8cfd-bff83de56707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmbFamilias-triggerWrap']/div[2]</value>
      <webElementGuid>01062977-3b77-4c3b-ac9d-b0b31e3bfab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>00919e1c-12fe-4444-ab7d-0f41c4668192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cmbFamilias-trigger-picker']</value>
      <webElementGuid>8a78fb6a-3283-43b2-a749-21ee88d4110e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
