<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_InicioTtulo WindowCascada WindowPERFILES1201</name>
   <tag></tag>
   <elementGuidId>0368c884-a8d7-456a-b905-3785bddb3cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl16-innerCt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl16-innerCt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0565d21c-e9e6-4a96-ae61-b7dd25d80c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl16-innerCt</value>
      <webElementGuid>0b704394-a65d-45ef-b4e3-4d668389f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>2b5bf9ae-8b44-4546-9e36-804a4b4842d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1c5f832b-bd85-41b3-8a93-c6632cc7269d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>b41eacb8-d406-4d93-b11b-e9696eb085aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inicio Título Window Cascada Window  PERFILES12:01</value>
      <webElementGuid>0d8f624a-aac7-414c-b71f-2b749027b809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl16-innerCt&quot;)</value>
      <webElementGuid>2b7e3718-f096-4cb8-87f9-03dbe7cb2482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ctl16-innerCt']</value>
      <webElementGuid>1868694f-de50-44b1-afd4-b27fc8c844c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl16']/div</value>
      <webElementGuid>e04d8619-6e59-4da3-85f0-e0a8ee7cccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>467e3238-0787-455d-8acf-d406da651a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ctl16-innerCt' and (text() = ' Inicio Título Window Cascada Window  PERFILES12:01' or . = ' Inicio Título Window Cascada Window  PERFILES12:01')]</value>
      <webElementGuid>602522db-2116-4f33-8594-7deb766a36a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
