<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_El registro ha sido modificado correctamente (2)</name>
   <tag></tag>
   <elementGuidId>ca15aef6-cb27-4832-8c44-72173fb5c821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#container-1004-innerCt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-1004-innerCt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b911a08-9d03-4d71-af0e-f443e8b48831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container-1004-innerCt</value>
      <webElementGuid>bb93a481-5d32-40af-98bf-fa53393fc7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>f17aafe7-c924-4d8e-8087-cf8bce136865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>d540acb9-11cf-4827-9c27-b956e66c4ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>a6131c68-6d55-42ef-ae81-c237856ae2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El registro ha sido modificado correctamente.</value>
      <webElementGuid>adf26061-7a23-496b-afd4-b1e4583af3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-1004-innerCt&quot;)</value>
      <webElementGuid>f36cad7d-2e20-4bd8-b987-a44a1b5055db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>1f26ba40-eb6f-4c93-9bbb-f95808776a3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='container-1004-innerCt']</value>
      <webElementGuid>61c5271f-fe4b-485b-8c0e-08c61cf4627f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-1004']/div</value>
      <webElementGuid>20c378ca-4f89-4028-b5d4-01e05ab53bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::div[6]</value>
      <webElementGuid>6adb79dc-ce4d-4d49-adab-16cb05f33fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sin Postor'])[1]/following::div[13]</value>
      <webElementGuid>3dfa215a-d71c-4965-8b5c-2ea522c0f38d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::div[24]</value>
      <webElementGuid>a034ee63-a7a0-410e-8284-2c29e41214fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div</value>
      <webElementGuid>0faa0093-b5df-44f0-8691-b8111e035d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container-1004-innerCt' and (text() = 'El registro ha sido modificado correctamente.' or . = 'El registro ha sido modificado correctamente.')]</value>
      <webElementGuid>fa7f3d55-f5d6-4c78-b722-2d81bc9103dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
