<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AceptarSNoCancelar</name>
   <tag></tag>
   <elementGuidId>8a5cb493-6279-4db5-a123-acda02a001eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#messagebox-1001-toolbar-innerCt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='messagebox-1001-toolbar-innerCt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>87630944-3193-4914-a4b3-c0108601f297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messagebox-1001-toolbar-innerCt</value>
      <webElementGuid>9ce13de8-be05-464f-a3e3-5fb96eaa8de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>innerCt</value>
      <webElementGuid>e91eff4b-eb43-4e63-a7e0-d3611d1a9b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4a8cde18-a220-4b3b-bdc2-a23c8c4bdbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-box-inner</value>
      <webElementGuid>5b3996b6-f56a-4575-9aab-b101b2d9ba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AceptarSíNoCancelar</value>
      <webElementGuid>0061f3c1-a1e3-4578-9a15-64a6b6a5598a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messagebox-1001-toolbar-innerCt&quot;)</value>
      <webElementGuid>5ece46ee-1b89-4a6c-9cd3-1f6d60c16d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Carga Masiva_ext-element-57</value>
      <webElementGuid>7f9d8072-5ca1-4c82-bfe6-1d44923003f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='messagebox-1001-toolbar-innerCt']</value>
      <webElementGuid>43fd9c1a-2030-444a-9af3-6dcf3543b945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='messagebox-1001-toolbar']/div</value>
      <webElementGuid>6ace7326-b761-4e5a-973d-24b68de83c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lotes cargado exitosamente.'])[1]/following::div[19]</value>
      <webElementGuid>a0f241b1-497a-4023-95c2-079f1b6cab9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceso terminado'])[1]/following::div[31]</value>
      <webElementGuid>6b0ca2da-37de-4d38-a6ee-8eeaf0e6a9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div</value>
      <webElementGuid>607c9679-9da3-4951-b12a-f0f60d704303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'messagebox-1001-toolbar-innerCt' and (text() = 'AceptarSíNoCancelar' or . = 'AceptarSíNoCancelar')]</value>
      <webElementGuid>e17d2840-9db9-4770-a8a2-a61e8086a3d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
