<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Lotes2548_IFrame</name>
   <tag></tag>
   <elementGuidId>1745c487-38fc-470e-89c3-927da26a1b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>23142a5b-5fec-4360-a7ee-cf52a801230c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>dbfd7723-6cee-49f8-b2b8-9cf49118c967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>6686f8fa-0b34-4f34-a7a8-90c8e56d0771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Lotes2548_IFrame</value>
      <webElementGuid>cf9a3c40-d6bb-4c6b-bd10-a7601047e839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745852533932</value>
      <webElementGuid>71389a35-795d-4c77-a437-f9395c3edafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3fd401c6-e0e7-4e09-9ca2-f1bb5c23a08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>b4c0962d-27c6-4914-818e-cf1b7c7454f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>8e1d22a5-32c9-4006-aefe-bce688b496a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Lotes2548-body']/iframe</value>
      <webElementGuid>45591e1f-3262-4570-b316-0aabfe7c56f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/iframe</value>
      <webElementGuid>ac35d556-0489-4b46-8fdf-bb980a13dfac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2548_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745852533932']</value>
      <webElementGuid>043e419a-7551-46ea-a2e8-fdc8892d9cba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
