<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_NMREM_IFrame_1</name>
   <tag></tag>
   <elementGuidId>ea9d4b42-c487-4b2a-8324-fa4f78f29dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1037</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1037']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8eda27c1-a642-4ee8-855c-88a2c5114d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>fccf5922-35ad-44ec-a98e-552c2e0363d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1037</value>
      <webElementGuid>abbd5b21-00d9-426e-b5f7-15615ea8beec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_NÓMREM_IFrame</value>
      <webElementGuid>52d15e88-8b62-41e3-a002-708f5660a1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1737471119530</value>
      <webElementGuid>72923130-e2f8-4dfa-90c2-bf37f67688d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>490fe978-3776-4e01-a621-9857dc15ed34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1037&quot;)</value>
      <webElementGuid>0a10045c-bed6-4340-be72-733d6af2c2e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1037']</value>
      <webElementGuid>47dbce70-e4cc-40b2-bcee-0102e89ce925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_NÓMREM-body']/iframe</value>
      <webElementGuid>c520f65d-6a35-404f-a9ca-de94a408f565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>836a68fb-3079-458a-93fd-f783ef69ac8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1737471119530']</value>
      <webElementGuid>cd27fd8d-45e4-48ba-8895-968acceae651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = 'javascript:false']</value>
      <webElementGuid>88ac4d0e-073a-4cf2-a782-9ed87bf4478c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
