<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_NMREM_IFrame</name>
   <tag></tag>
   <elementGuidId>3b49a3f2-a2de-44b5-a85b-ecf553bb6818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1037</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1037']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b0fd92f2-7ac4-4199-a546-c71af9785dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>eec6cd5e-539a-4d45-8115-d3a2f36a81a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1037</value>
      <webElementGuid>58e1d4e3-9cd7-4b59-b1c5-23c314a8f3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_NÓMREM_IFrame</value>
      <webElementGuid>3b7876a6-80ec-432c-bf25-6b5eae461416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1745852506266</value>
      <webElementGuid>8ec031f1-364f-45ab-bc21-59c96e8d10c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69ef74f6-1561-4fd5-9dd2-db60a20035c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1037&quot;)</value>
      <webElementGuid>6bbceae2-0843-42c2-b02a-b4db30d7db68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1037']</value>
      <webElementGuid>4382b7df-142d-4dc9-9e4a-6b1ebe0f76f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_NÓMREM-body']/iframe</value>
      <webElementGuid>194fcfc7-0732-4eac-b155-25080cc90aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d9cc63fd-85fc-415a-abe6-44d17908a4a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1745852506266']</value>
      <webElementGuid>a5df49e6-ad7a-48e6-9893-0cf69054d5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1736520207904']</value>
      <webElementGuid>8a5dcae4-28ca-48e3-ae89-196e2334f088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1735653075941']</value>
      <webElementGuid>292b22d5-ac12-4d33-a588-cc7a267c1f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1735652148959']</value>
      <webElementGuid>39b83b92-83b4-465b-85c2-51044a7d9294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1735651436155']</value>
      <webElementGuid>c74cca2f-b073-46c7-b134-f65f4d380cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1735648770076']</value>
      <webElementGuid>f0f79a42-0933-4dbe-955e-bd2ce6da3d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1735583204702']</value>
      <webElementGuid>0b346752-0de0-4dcb-b094-6cd2ef33b0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1734364845202']</value>
      <webElementGuid>d9fc923d-4310-4fdf-b4b0-0afc3ee359d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
