<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Lotes2555_IFrame_1</name>
   <tag></tag>
   <elementGuidId>2ddff131-d070-42b2-ad01-7da4f7cce4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c9872347-0fc1-4389-8263-6539cd47bcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>d02f167f-1b51-49ad-8e8d-0ad0176ea001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>42ea538f-698e-414e-bf5c-67d13ccded6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Lotes2555_IFrame</value>
      <webElementGuid>6320891c-e603-47b3-819f-dccf02ff1ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Administracion/wf_pa_loteos_Simple.aspx?id_remate=2555&amp;parent=WIN_Lotes2555&amp;_dc=1737492555471</value>
      <webElementGuid>b1807052-e2ec-46fd-a4e3-299171bc6b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce0dc293-c4bc-48fd-b4dd-8cf6ff63c396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>ace952fa-70e7-46ca-8aba-41c7e17a0c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>62096538-a53a-4c94-9466-4c1df651adc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Lotes2555-body']/iframe</value>
      <webElementGuid>ba043097-4155-4080-b2ff-95eebe3a8a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/iframe</value>
      <webElementGuid>a4666de3-7ae3-4308-a382-a989cb0b4ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2555_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2555&amp;parent=WIN_Lotes2555&amp;_dc=1737492555471']</value>
      <webElementGuid>21b56a39-9588-4b4c-8372-937a3d879412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/iframe</value>
      <webElementGuid>f60a2d45-dcee-4dda-b104-9ac235ca6a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2555_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2555&amp;parent=WIN_Lotes2555&amp;_dc=1737484557451']</value>
      <webElementGuid>fcab2438-577a-4962-af8c-ca1b6c6c1926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
