<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(Imagenes de Lote N1 - , , BICICLETA, , )_ext-element-64</name>
   <tag></tag>
   <elementGuidId>f90df850-3398-4abc-9b4c-50d954abb512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ext-element-64</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ext-element-64']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b0239173-10bf-4fe9-979b-7afd7b566468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>529469a1-34df-4c06-b16c-91ff0d13679a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2df24938-44ca-4581-840d-ce0f9a1d92cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be857a13-aa1c-4b30-aaf2-da9852567d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b62785fe-1a41-46e9-8885-e5af96e29e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6f471153-7b9e-46d2-bbbd-9d0b36896984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../ModuloImagenes/#!/app/images/73916/1/49/2548</value>
      <webElementGuid>656104e7-8320-4091-9b07-72143fb04eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>513224160d5cee0c05c6d2edca0fc6b2</value>
      <webElementGuid>d9e95350-60aa-4fe4-bc4a-0027d7f6bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-64</value>
      <webElementGuid>5c9d5d48-7bcb-4c0e-bf95-db8d7c69e1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-64&quot;)</value>
      <webElementGuid>9c4548de-f114-4c14-8751-6344e56bd523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2548_IFrame_1_2</value>
      <webElementGuid>0bc23576-6156-419a-a14c-ca8780ef0320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ext-element-64']</value>
      <webElementGuid>44301e1d-bed9-4b29-a1d9-3e83a58a2c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='winMantenedor-innerCt']/iframe</value>
      <webElementGuid>2a07a450-528e-4704-85fb-7783fda4a0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fe0439ac-ce20-4554-973e-41330f287cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '../ModuloImagenes/#!/app/images/73916/1/49/2548' and @id = 'ext-element-64']</value>
      <webElementGuid>1a8e65eb-85b3-4aaf-9b7b-6d9f9b9beca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
