<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Lotes2554_IFrame</name>
   <tag></tag>
   <elementGuidId>36de37de-7838-44b9-b992-844dbef64047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ddefc409-b7e9-4461-bc47-aff2d2448f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>abbb1feb-8ef6-4daa-8c8b-20746bcd58c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>8c364bd1-d3e6-48bf-a48b-8c1e600f6d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Lotes2554_IFrame</value>
      <webElementGuid>1c44d9da-05f7-4316-bb9d-20fe5f7f7765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Administracion/wf_pa_loteos_Simple.aspx?id_remate=2554&amp;parent=WIN_Lotes2554&amp;_dc=1735648782194</value>
      <webElementGuid>a979e52b-332e-4747-b36e-699fb6874ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f91fcf0-b1d1-4e51-8c42-86914c8f907f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>e6583c97-7d05-401e-9632-31817b280532</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>42e7acb9-c2fc-4c7c-a6e6-f9313e7cf077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Lotes2554-body']/iframe</value>
      <webElementGuid>f3f685cf-96e2-4f37-997b-2d8735508821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/iframe</value>
      <webElementGuid>6538c477-944a-422e-a6c1-72e77c875297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2554_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2554&amp;parent=WIN_Lotes2554&amp;_dc=1735648782194']</value>
      <webElementGuid>e43fd51f-1d9b-4f97-906c-2d3ac1e280d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
