<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_NMREM_IFrame_1_2</name>
   <tag></tag>
   <elementGuidId>f0732788-41ac-4344-a403-103ebfb0d981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1037</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1037']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d438113d-f06f-4e37-befa-5ca64f8e4cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>faf3a0a9-5061-48b3-a902-7d41b4dd4083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1037</value>
      <webElementGuid>23d8ca39-fd9c-482b-a98e-ff3bdea0173e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_NÓMREM_IFrame</value>
      <webElementGuid>f6b0ebdf-b245-4929-a954-7e3591bb1eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1737492549504</value>
      <webElementGuid>cec7fa5b-c9c2-4863-aa95-b030b30ffd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb313d4c-3105-4734-a866-40379f24fd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1037&quot;)</value>
      <webElementGuid>114edf53-45e8-4441-8669-c0c389976c57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1037']</value>
      <webElementGuid>4779793b-a808-41b7-8b51-66c56cdd41b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_NÓMREM-body']/iframe</value>
      <webElementGuid>6c6b15dd-008f-49b0-bf1f-19252b2d5321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2f835d95-6d7f-402f-86b6-51f49b79f7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1737492549504']</value>
      <webElementGuid>92a736ab-0819-43ba-84d1-9270c06f3739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1037' and @name = 'WIN_NÓMREM_IFrame' and @src = '/qa_rel_vacio_04/admin/Administracion/wf_pa_re_remates_no.aspx?id_rematetipo=1&amp;k=79&amp;u=122&amp;p=47&amp;parent=WIN_NÓMREM&amp;_dc=1737484511778']</value>
      <webElementGuid>f7f5c6dd-6551-4a98-b279-14e5d7a3e51f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
