<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Garantia2554_IFrame_1</name>
   <tag></tag>
   <elementGuidId>8effbc93-2a97-4289-83d4-6b43753e25c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f21d4140-6f56-4f4d-9956-f46284747d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>a7e3a31a-965c-43a0-a852-37b65244823e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>bcccf4e1-1cae-446d-82e8-bef517d013db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Garantia2554_IFrame</value>
      <webElementGuid>d2532e7c-1993-4294-b432-2bcbb69d97b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qaplg.plataformagroup.cl/QA_REL_VACIO_04/admin-remate-linea/loginExterno?token=dDZzN1NOTDhxbjg4YUVnQ3YrZzYwUT09&amp;parent=WIN_Garantia2554&amp;_dc=1735652185955</value>
      <webElementGuid>6ab1668b-c135-4248-b34f-7d71dc9c83fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>eadd1822-4804-47d5-ac1d-6780c40e7f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>f38c5e84-f098-4039-891e-4f8425ac6fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>eb3fd65d-34b8-440c-90bb-04de319dcbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Garantia2554-body']/iframe</value>
      <webElementGuid>646a50d5-a144-411e-8ebf-e9bc540674fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/iframe</value>
      <webElementGuid>aba5ef3e-2771-41a2-a7e0-f82db4d3eac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Garantia2554_IFrame' and @src = 'https://qaplg.plataformagroup.cl/QA_REL_VACIO_04/admin-remate-linea/loginExterno?token=dDZzN1NOTDhxbjg4YUVnQ3YrZzYwUT09&amp;parent=WIN_Garantia2554&amp;_dc=1735652185955']</value>
      <webElementGuid>2ed9016a-2db1-4410-a985-450f4f800d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
