<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Lotes2548_IFrame_1</name>
   <tag></tag>
   <elementGuidId>eaba6a44-fc36-496b-9bee-a4047c36622d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3c30cfa1-68c2-4a57-9967-39d13eddec56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>95583769-b907-4fb4-8755-ec66b3462825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>8ed8c6b9-72fd-4ff3-8027-79895fde1cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Lotes2548_IFrame</value>
      <webElementGuid>f8e6e5b0-3959-41ab-a4af-ddd3d353848c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745857705751</value>
      <webElementGuid>40739f9b-2ae2-4a78-bf6d-1aeb0be264f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>499fa55b-24f3-49f5-b5ec-3dc829f3e311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cd_frame_id_</name>
      <type>Main</type>
      <value>1cfa99aec754e8f3e2b3afbb40c6e9d6</value>
      <webElementGuid>e385b618-e106-4d6b-a7ba-c1c7d84ab165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>fe9794b0-665c-4756-9cb9-a2113baedf4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>095a2ee2-1a63-4d19-b76c-000e91d6f013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Lotes2548-body']/iframe</value>
      <webElementGuid>31d7c575-a3d8-4a1a-992f-30daf137f024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/iframe</value>
      <webElementGuid>c066c476-5642-4f23-b7f8-1f3aaaca8db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2548_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745857705751']</value>
      <webElementGuid>61476fa8-b88b-4ce2-8107-abd6021c3a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2548_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745857427498']</value>
      <webElementGuid>ad2999a4-79ff-4074-9784-069fe7ded913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2548_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745856799713']</value>
      <webElementGuid>403c65f5-1dc4-449f-8c18-54bce49ade3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2548_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2548&amp;parent=WIN_Lotes2548&amp;_dc=1745853755507']</value>
      <webElementGuid>e33262ee-7c57-4910-860e-5d85df698476</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
