<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Garantia2554_IFrame</name>
   <tag></tag>
   <elementGuidId>e3aaae0f-12ad-4687-86a1-dcc6305024d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1057</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1057']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8b0b050a-b646-4a75-bb0a-a3d4a741bfeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>8f011e67-5064-4a44-b736-ccd5f6195434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1057</value>
      <webElementGuid>696a374e-e3fb-4010-8822-860ffd6fd2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Garantia2554_IFrame</value>
      <webElementGuid>8a73898e-e844-48ba-9494-96ea7279f594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qaplg.plataformagroup.cl/QA_REL_VACIO_04/admin-remate-linea/loginExterno?token=dDZzN1NOTDhxbjg4YUVnQ3YrZzYwUT09&amp;parent=WIN_Garantia2554&amp;_dc=1735651535518</value>
      <webElementGuid>cea87196-c507-4ffb-a95d-7ccf6c908c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dee0aa2e-3bf4-4c56-9773-84abd2bdfe06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1057&quot;)</value>
      <webElementGuid>9c8eba07-73fa-4da4-b9c7-90988d6869ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1057']</value>
      <webElementGuid>8605e082-e79b-4119-aa3c-7de4c68d97cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Garantia2554-body']/iframe</value>
      <webElementGuid>530ca19c-b312-4411-b670-c7a415230172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/iframe</value>
      <webElementGuid>66ebbebd-5cd5-4b05-bb44-3b8ac0a0b712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1057' and @name = 'WIN_Garantia2554_IFrame' and @src = 'https://qaplg.plataformagroup.cl/QA_REL_VACIO_04/admin-remate-linea/loginExterno?token=dDZzN1NOTDhxbjg4YUVnQ3YrZzYwUT09&amp;parent=WIN_Garantia2554&amp;_dc=1735651535518']</value>
      <webElementGuid>e4d955a3-577c-47a6-8cff-9e481732fe5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
