<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Agregar Remate_WIN_Agregar_IFrame</name>
   <tag></tag>
   <elementGuidId>a6d11e25-05c0-4bc5-a660-91013b979e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>46af37c9-a99e-45e2-9861-8f07ea9932ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>20126c8f-f34c-4700-9da1-04e3ab81c7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>814fa687-2088-456c-b05f-caf303ead148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Agregar_IFrame</value>
      <webElementGuid>2f9a4e71-1d5d-435e-9f66-c3fae506823d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Administracion/wf_re_remates_adm.aspx?id_rematetipo=1&amp;id_remate=0&amp;op=in&amp;esad=0&amp;parent=WIN_Agregar&amp;_dc=1735323591201</value>
      <webElementGuid>14533427-1893-4711-afbc-e39415852d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb25eff5-a42d-4602-bf79-99e9dabca7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>3d39f943-eba3-45e8-a7c4-1dc4abe82d8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>d7785f18-1be5-4c79-8d91-cc55c7a78a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Agregar-body']/iframe</value>
      <webElementGuid>e6cacef4-1633-43d1-8ca5-3dfa02224533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/iframe</value>
      <webElementGuid>60900b71-b63f-4b95-a9e2-f688567bd56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Agregar_IFrame' and @src = 'Administracion/wf_re_remates_adm.aspx?id_rematetipo=1&amp;id_remate=0&amp;op=in&amp;esad=0&amp;parent=WIN_Agregar&amp;_dc=1735323591201']</value>
      <webElementGuid>5f99e91f-5704-4743-992f-cf6d1bf23a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/iframe</value>
      <webElementGuid>cfe0e38b-f6c1-4edb-bcff-a5479ced34e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Agregar_IFrame' and @src = 'Administracion/wf_re_remates_adm.aspx?id_rematetipo=1&amp;id_remate=0&amp;op=in&amp;esad=0&amp;parent=WIN_Agregar&amp;_dc=1734364876150']</value>
      <webElementGuid>72a4bf01-73ba-4747-a424-870f8632088d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
