<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Nmina Remates_WIN_Lotes2556_IFrame</name>
   <tag></tag>
   <elementGuidId>809d788e-3885-4966-987f-65e94a2f55d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#component-1047</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='component-1047']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4015f92e-2ec9-484c-b0e8-11242ffc8f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-component x-fit-item x-window-item x-component-default</value>
      <webElementGuid>56a66a6f-8480-4484-a4b3-8c3a0f596d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>component-1047</value>
      <webElementGuid>382b5369-d931-496f-bf9e-66800aa5a426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WIN_Lotes2556_IFrame</value>
      <webElementGuid>14f8e514-d4c1-49fd-8983-3b5efaca8d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Administracion/wf_pa_loteos_Simple.aspx?id_remate=2556&amp;parent=WIN_Lotes2556&amp;_dc=1736520248823</value>
      <webElementGuid>4a95a190-5eb3-439d-9746-ec30286443a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f5824d97-4515-4de8-811f-c7108f7c3b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;component-1047&quot;)</value>
      <webElementGuid>89331797-7f42-419c-a6b4-1f7e544faeb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='component-1047']</value>
      <webElementGuid>033af8a1-657d-4d2c-937e-4783d24e5a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WIN_Lotes2556-body']/iframe</value>
      <webElementGuid>6efac0b9-17fb-442d-b1bb-9e5bbcaad6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/iframe</value>
      <webElementGuid>9bf2e2d6-e9d2-4354-a871-e63f018c82b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'component-1047' and @name = 'WIN_Lotes2556_IFrame' and @src = 'Administracion/wf_pa_loteos_Simple.aspx?id_remate=2556&amp;parent=WIN_Lotes2556&amp;_dc=1736520248823']</value>
      <webElementGuid>8313010b-aa3e-4413-aa98-319271cd9c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
