<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nmina Remates_tool-1041-toolEl</name>
   <tag></tag>
   <elementGuidId>30b4c410-b942-4e92-a8ac-ad4240a07c0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tool-1041-toolEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='tool-1041-toolEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4821853-fa49-4c6b-acd0-67514c4bb3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tool-1041-toolEl</value>
      <webElementGuid>af30222d-560a-4895-aa7b-707c3655eceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>toolEl</value>
      <webElementGuid>76cbf8cb-fc7f-4c17-9c50-3a0a2a505632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==</value>
      <webElementGuid>62d72dc1-cd23-480d-b977-907e40a76bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-tool-img x-tool-close</value>
      <webElementGuid>0987b3d9-741e-4043-b52b-1d52d4d75991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>0cf9017d-efc6-4109-ab91-59e10e7b5df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tool-1041-toolEl&quot;)</value>
      <webElementGuid>be72b818-bd5a-44b2-bbac-9f430173c47a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='tool-1041-toolEl']</value>
      <webElementGuid>46f218c3-7521-4bd7-b513-d03d5cd0c822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tool-1041']/img</value>
      <webElementGuid>6deb8b52-360d-456f-bd1d-c5b6665edd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==')])[9]</value>
      <webElementGuid>9df5db63-96b0-4b50-8e91-a52f5fda8c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div[4]/img</value>
      <webElementGuid>53023eef-3c76-4fb9-9eba-4f56777107f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'tool-1041-toolEl' and @src = 'data:image/gif;base64,R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==']</value>
      <webElementGuid>cdc61c0f-d936-4100-aa34-998ef6191428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div[4]/img</value>
      <webElementGuid>74179ef9-0316-4c4c-a1d8-ab00f95e6d25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
