<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Inicio_ext-element-3</name>
   <tag></tag>
   <elementGuidId>95121a56-350a-41c5-b7b5-a189976b520c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ext-element-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ext-element-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f4b7e4a0-6de0-492f-9c04-be017476bbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/QA_REL_VACIO_04/Admin/Resources/images/desktop/powered.png</value>
      <webElementGuid>f05626fb-1a3c-4b7f-9328-a3a62ab75c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ext-element-3</value>
      <webElementGuid>8e898ab4-2169-41c4-8333-75432be2e8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ext-element-3&quot;)</value>
      <webElementGuid>6b043bc4-3446-44e1-adf3-1c959b84e281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ext-element-3']</value>
      <webElementGuid>be4f055b-abe4-4552-a609-46604410cb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl33']/img</value>
      <webElementGuid>09d20792-3e9a-4bf9-a778-039c4659f8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>765b5bf2-d4ce-4f03-ac0f-2f8719aba93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/QA_REL_VACIO_04/Admin/Resources/images/desktop/powered.png' and @id = 'ext-element-3']</value>
      <webElementGuid>c12abe24-d956-48a5-8b78-ee7283d16910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
