<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtPorcentajeGarantia</name>
   <tag></tag>
   <elementGuidId>ab49fea7-8f43-4067-bf9e-1e53ddd01aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtPorcentajeGarantia-inputEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtPorcentajeGarantia-inputEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ee38178-d1c6-4983-ac0c-8aed427f5ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPorcentajeGarantia-inputEl</value>
      <webElementGuid>2c506fe0-fb9f-4502-af9d-515f148b2c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>inputEl</value>
      <webElementGuid>2886b906-1004-4da2-be72-0480dfda7d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef3551a0-6058-4c58-b449-c7563733539b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>edd3706c-daa2-40e9-8dc4-a414d5ec9ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2f30b743-fc93-471b-9278-8d4c2b2054cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtPorcentajeGarantia</value>
      <webElementGuid>e563a994-07b1-423a-813f-4ba288a043b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-field x-form-required-field x-form-text x-form-text-default  </value>
      <webElementGuid>fa0dbad4-b212-43f1-991f-064aed352b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7b28455-acf5-4e53-b8d6-f52cbedb0f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>componentid</name>
      <type>Main</type>
      <value>txtPorcentajeGarantia</value>
      <webElementGuid>ab6e795a-e9c7-4873-86b7-13d4f0558fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPorcentajeGarantia-inputEl&quot;)</value>
      <webElementGuid>340f2102-149f-4c7a-b8cc-625c23645d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>262076ec-feb0-4682-98dd-6ea0784b49df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtPorcentajeGarantia-inputEl']</value>
      <webElementGuid>5484a0c5-572d-4770-b0d1-1f98857b987a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='txtPorcentajeGarantia-inputWrap']/input</value>
      <webElementGuid>d00e6f17-64be-4dc0-9508-22f6a885feb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>1bd3da3c-eeb2-4527-be61-3db80a668dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtPorcentajeGarantia-inputEl' and @type = 'text' and @name = 'txtPorcentajeGarantia']</value>
      <webElementGuid>a24164d4-3b4d-42fb-9e6d-1a586d6d1d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
