<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_NO PUBLICADO</name>
   <tag></tag>
   <elementGuidId>56407955-d4ca-4d96-b01c-acf4524682b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='boundlist-1145-listEl']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.x-boundlist-item.x-boundlist-item-over</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>46e60302-6f16-4d25-af88-1d92154508e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fb72c749-bf45-434d-b7ce-f7cdb1686519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6d66c3fd-faa0-4261-9e73-b389a743038e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-item-over</value>
      <webElementGuid>4530c773-6183-4c85-9eb1-e85f5fb729d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>391a7844-17f4-4179-84d7-8bee498accca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>32220bb2-8d73-4b69-afe8-404b446ab04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>171</value>
      <webElementGuid>9aaa5a31-2a6d-41c3-9183-d6d90ff1908f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>boundlist-1145</value>
      <webElementGuid>45af3d3c-e7c9-42bb-ac09-e946eddcfc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NO PUBLICADO</value>
      <webElementGuid>e8dd5408-570d-4491-abde-d4bd0bd142d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boundlist-1145-listEl&quot;)/li[@class=&quot;x-boundlist-item x-boundlist-item-over&quot;]</value>
      <webElementGuid>8bb7a130-3d2e-4186-907f-64a2535fce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>237732de-2a69-4659-93a7-36214da244fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='boundlist-1145-listEl']/li[2]</value>
      <webElementGuid>8d8be80d-4434-4f5e-a4ce-bf3c43d0e29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN PREPARACIÓN'])[1]/following::li[1]</value>
      <webElementGuid>271e6f96-8f5e-49e7-aa4d-213852eabefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESTE ED'])[1]/following::li[2]</value>
      <webElementGuid>b961732e-a5c3-45b7-8d6c-9c40940a3476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PREVISUALIZACIÓN'])[1]/preceding::li[1]</value>
      <webElementGuid>8351e709-f1e5-4244-97a8-f45c1e7cb5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[1]/preceding::li[2]</value>
      <webElementGuid>354e4bcf-bae7-49ff-8718-8fe3c73b44cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NO PUBLICADO']/parent::*</value>
      <webElementGuid>63b540f5-4637-49a5-b893-7bf13d919cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[2]</value>
      <webElementGuid>5901e141-9a3a-4e31-abc7-b799adf014ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'NO PUBLICADO' or . = 'NO PUBLICADO')]</value>
      <webElementGuid>e6382154-c43c-42f9-ac35-a618666b1f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
