<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Remate</name>
   <tag></tag>
   <elementGuidId>a162fd6d-749b-49fb-aa92-42791e00833d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='boundlist-1146-listEl']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.x-boundlist-item.x-boundlist-selected.x-boundlist-item-over</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>41ce844d-cda9-4458-ac33-bd771384e545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0e63f360-34b0-4359-920e-9da8d4595119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>211365a4-6a1c-4372-86e9-b82410da6c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-boundlist-item x-boundlist-selected x-boundlist-item-over</value>
      <webElementGuid>76128950-d712-4e57-8164-9b1395c296e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5db87c38-04af-428c-9c5c-b4a4104f7892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7ba98d7d-2bd4-41fa-abec-a1f734e61718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>176</value>
      <webElementGuid>ee7f270d-eca4-4529-a8f1-6c43b13a854c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-boundview</name>
      <type>Main</type>
      <value>boundlist-1146</value>
      <webElementGuid>c5a26e22-1a18-409f-b180-cb92fc070a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remate    </value>
      <webElementGuid>8c74f770-ec57-4b9f-9b88-178ba1456de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boundlist-1146-listEl&quot;)/li[@class=&quot;x-boundlist-item x-boundlist-selected x-boundlist-item-over&quot;]</value>
      <webElementGuid>4ec781e6-12da-478a-8662-732bca561bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Agregar Remate_WIN_Agregar_IFrame</value>
      <webElementGuid>16219135-f6fc-4029-9a6a-cae5b7edf121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='boundlist-1146-listEl']/li[2]</value>
      <webElementGuid>ba856650-4fcb-48e6-9b0d-2fdf798c1e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Licitación'])[1]/following::li[1]</value>
      <webElementGuid>1dcb48d2-fd06-4c8f-8798-a05ab0ea3a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMATE FINALIZADO'])[1]/following::li[2]</value>
      <webElementGuid>53d59211-0027-4bbb-92e0-7a5133164787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remate']/parent::*</value>
      <webElementGuid>48c5f5be-6fb9-45fe-bc80-721bc79d8692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[2]</value>
      <webElementGuid>c8b59edf-3614-4bb4-8ef3-d45e9f4ff7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Remate    ' or . = 'Remate    ')]</value>
      <webElementGuid>4d50c683-78ab-4236-a0d7-639a9bd083bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
