<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Nmina Remates</name>
   <tag></tag>
   <elementGuidId>940f70a9-8557-4d8f-9229-388628c03fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MH_NÓMREM-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='MH_NÓMREM-textEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9ce0deec-485b-4d3b-8800-c12924e3eb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH_NÓMREM-textEl</value>
      <webElementGuid>fd82a0bd-92cd-4535-b8b1-0da1e720c4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>b5251243-dfc5-4ba4-a721-faceef8e6ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-text x-menu-item-text-default x-menu-item-indent</value>
      <webElementGuid>dff9a0e3-735b-4cf0-b1f1-f3b045504c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a156ce68-5572-4295-b629-357ac31a2960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nómina Remates</value>
      <webElementGuid>a3fca14c-7a70-44e2-b9a3-39d1582fbdc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH_NÓMREM-textEl&quot;)</value>
      <webElementGuid>46fd489c-85b3-4c91-9ded-932a1a9f3066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='MH_NÓMREM-textEl']</value>
      <webElementGuid>c393651b-3434-465c-97bb-aeeaecc6d58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='MH_NÓMREM-itemEl']/span</value>
      <webElementGuid>19a03974-33e4-4469-9f17-bbd402dacef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar Sesión'])[1]/following::span[1]</value>
      <webElementGuid>80d0b717-0cb2-495f-9556-827a94257198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerca de'])[1]/following::span[5]</value>
      <webElementGuid>a770d799-f242-4bd6-8084-74babe8c1373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandantes'])[1]/preceding::span[1]</value>
      <webElementGuid>33c5ce59-d8fd-449e-b8b7-df878c02ae09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nómina Remates']/parent::*</value>
      <webElementGuid>39a782c0-909b-474d-8aed-c098fba5890f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div/div/a/span</value>
      <webElementGuid>d69a97de-57ff-440b-b03b-637eeb912764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'MH_NÓMREM-textEl' and (text() = 'Nómina Remates' or . = 'Nómina Remates')]</value>
      <webElementGuid>d4cebb55-de5d-41bb-9a4e-f402ff25014c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personas'])[1]/following::span[1]</value>
      <webElementGuid>a8d255b1-6323-4861-ae39-4469fa746eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nómina Perfiles'])[1]/following::span[2]</value>
      <webElementGuid>0c78b466-3e1a-4fef-86e5-3018d80adcc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[3]/div/div/a/span</value>
      <webElementGuid>33737b34-eb4e-4ef7-b19d-79015dfb1970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informe resultado remate'])[1]/following::span[1]</value>
      <webElementGuid>4751c55b-3a16-4839-997e-9bed2bd0e32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Familia, Categorías, Subcategorías'])[1]/following::span[2]</value>
      <webElementGuid>b80ae13d-db89-4ce8-9a1f-095afe185c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[3]/div/div/a/span</value>
      <webElementGuid>61107040-1561-4ed3-9d00-39f81a9bcb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/preceding::span[2]</value>
      <webElementGuid>8a512e76-755e-42e6-ba61-74741bd7b9ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
