<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aceptar (1)</name>
   <tag></tag>
   <elementGuidId>6e142246-af62-48f5-abab-6361d248ca0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1005-btnEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1005-btnEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21169eb5-8e5d-4ca7-81a3-2f02e2bf9d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1005-btnEl</value>
      <webElementGuid>3c9c0fed-6a78-4c99-993d-373b1e7acaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnEl</value>
      <webElementGuid>cb7cf873-93f1-4f1b-838c-68fda6070d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>0b7b9dce-a2f4-41df-8eea-edfb73ebe782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6026e60d-13f9-4a4d-8b9c-5ac1ca549e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-button x-btn-button-default-small x-btn-text    x-btn-button-center </value>
      <webElementGuid>d7eeddb9-bf83-4562-b27f-e05349bb3eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>8422b96a-3f6a-4df8-a1c6-d35b7259079b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1005-btnEl&quot;)</value>
      <webElementGuid>3c560753-f600-4078-a702-9ff922d4b0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>a8f99575-3798-4d39-9474-317817a07929</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnEl']</value>
      <webElementGuid>2f38d255-6e2b-4d7d-bfa7-b79b4d83b4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1005-btnWrap']/span</value>
      <webElementGuid>d78fb777-fdfa-4a71-a805-eb244a656448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El registro ha sido modificado correctamente.'])[1]/following::span[4]</value>
      <webElementGuid>b9a82715-e8f7-4fe1-8208-915ccaed7d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/following::span[4]</value>
      <webElementGuid>e420a82a-9c5b-411a-9b20-3f83e00dfd32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sí'])[1]/preceding::span[4]</value>
      <webElementGuid>9d44eb43-4db3-4379-84d3-59ec1ad37380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/a/span/span</value>
      <webElementGuid>b1aff1de-c626-4416-8653-0078c0ba14a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1005-btnEl' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>ebcbb54f-6085-45fd-91ed-ce29e6c066d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
