<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Editar Lote</name>
   <tag></tag>
   <elementGuidId>e2c8dce1-208b-446c-9622-3a0b847a968d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuitem-1132-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='menuitem-1132-textEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1abccc18-9c8d-42f8-b10e-c46de57739fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuitem-1132-textEl</value>
      <webElementGuid>a2f6c15e-0da7-49c8-b08e-bbbf95301332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>f7c6c9e7-61b5-4792-b247-65f5ddca42c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-text x-menu-item-text-default x-menu-item-indent-no-separator</value>
      <webElementGuid>732fc652-e13a-4b3c-9c7c-303d2501a634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>69a2937b-645a-47ca-aa36-9419f84e41f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar Lote</value>
      <webElementGuid>c1c4736c-ed4c-4ddc-bba4-f9134bd38d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuitem-1132-textEl&quot;)</value>
      <webElementGuid>c4082e51-4830-4705-b2b1-91cdd2614ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2555_IFrame_1</value>
      <webElementGuid>0b633c59-7e00-4cc7-aaa8-0b5c6567c362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menuitem-1132-textEl']</value>
      <webElementGuid>6307f2ad-0c80-4dab-b48e-f68548b663ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuitem-1132-itemEl']/span</value>
      <webElementGuid>d9378fb0-c877-46d7-936b-15af9d1cbab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Minor Version Upgrades Included!'])[1]/following::span[1]</value>
      <webElementGuid>7446e161-7938-49a3-a029-47eb3f93dd0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PURCHASE LICENSE'])[1]/following::span[1]</value>
      <webElementGuid>39001e1f-9045-4f36-88dd-f4eb965018b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imágenes Lote'])[1]/preceding::span[1]</value>
      <webElementGuid>aed74882-9ce8-4ccf-9620-b2fd90428196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lotes con Derecho'])[1]/preceding::span[2]</value>
      <webElementGuid>a92283cf-db49-4df5-9777-12dee4e457d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editar Lote']/parent::*</value>
      <webElementGuid>9e760579-f1fe-454f-a040-bfa35dc3431e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span</value>
      <webElementGuid>95cbff44-55b7-4638-af22-4fba55eac1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menuitem-1132-textEl' and (text() = 'Editar Lote' or . = 'Editar Lote')]</value>
      <webElementGuid>9af9eba2-7104-4624-a21d-d5d5cd3c4ea5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
