<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Lotes Remate (1)</name>
   <tag></tag>
   <elementGuidId>860abd2a-4269-49ff-aaa8-181280c92866</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuitem-1145-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='menuitem-1145-textEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40f37265-bc9e-45bd-aa9d-de9e6138ebc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuitem-1145-textEl</value>
      <webElementGuid>3e730e27-3457-40b4-91d5-25e8573ccadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>c1268837-40b3-4c6c-b06e-58232de784c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-text x-menu-item-text-default x-menu-item-indent</value>
      <webElementGuid>eadd25ab-677e-497b-bd9f-73b3d3da8843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>2483977a-2a76-4ea0-81fe-515b9b6b9aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lotes Remate</value>
      <webElementGuid>5b3995b0-2557-4396-b6df-859a8134532a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuitem-1145-textEl&quot;)</value>
      <webElementGuid>27cd7e8f-19db-41c0-bf17-27a2ed533d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_NMREM_IFrame_1_2</value>
      <webElementGuid>270ac678-afb9-4da3-85f2-55bfdcd868b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menuitem-1145-textEl']</value>
      <webElementGuid>1e6a1bfa-161c-4d9b-8c6d-c70e4fcfefe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuitem-1145-itemEl']/span</value>
      <webElementGuid>bd597e32-0d6f-47df-9acf-3304f463f03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Imágenes Remate'])[1]/following::span[1]</value>
      <webElementGuid>415848db-ccea-47ea-b955-244d2a53e271</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar Remate'])[1]/following::span[2]</value>
      <webElementGuid>5d039c2e-debf-4334-b7ad-10382f00acfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar Catálogo'])[1]/preceding::span[1]</value>
      <webElementGuid>c486c073-8cd2-4499-a921-a090bc8313e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar Acta'])[1]/preceding::span[2]</value>
      <webElementGuid>9d8d6080-bf59-4567-a34b-c5700cd9709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lotes Remate']/parent::*</value>
      <webElementGuid>7e8cd8f9-b7cd-48f3-a698-4038ad994d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/span</value>
      <webElementGuid>1804e965-578f-4505-b265-ffe1d4a0b83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menuitem-1145-textEl' and (text() = 'Lotes Remate' or . = 'Lotes Remate')]</value>
      <webElementGuid>e63e409a-1139-46e7-91f8-d2cc5ec15345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
