<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Inicio</name>
   <tag></tag>
   <elementGuidId>3f7a25d3-2358-4cd7-b75e-d47f46226f8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1017-btnWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1017-btnWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3911b44-b081-4b81-a771-9740bc998211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1017-btnWrap</value>
      <webElementGuid>1fa4fdd4-d862-49e4-86d6-c85272f61d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnWrap</value>
      <webElementGuid>3d58df19-60f3-488a-bcae-e7f98f9d3dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>037426c0-e9c9-4b67-95a3-0875139b7877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>dfe72382-ff54-4b06-80bf-165f704ad92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-wrap-default-toolbar-small x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>baddd066-bc7c-4f6b-acf3-f25ff0ff143d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Inicio</value>
      <webElementGuid>ee598d39-98a3-4d16-a751-4651f3038467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1017-btnWrap&quot;)</value>
      <webElementGuid>98ff0f62-421f-4052-9238-521f43e5d71d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1017-btnWrap']</value>
      <webElementGuid>16e8b699-daa2-4c6d-846f-98df95410c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1017']/span</value>
      <webElementGuid>057dd234-c4a9-440f-9537-03874265c54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Título Window'])[1]/preceding::span[5]</value>
      <webElementGuid>3a72de5e-5f09-4643-a759-1a2de48b4763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>0583988e-f98a-4094-b1b2-0353a965bd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1017-btnWrap' and (text() = ' Inicio' or . = ' Inicio')]</value>
      <webElementGuid>7fbdf945-f9d4-4d0d-ac8d-caff9baf107b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1017-btnInnerEl']</value>
      <webElementGuid>fc9da392-f868-433c-961d-ca6ea755852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1017-btnEl']/span[2]</value>
      <webElementGuid>ea827e38-f74d-48cb-b247-695d2f6336fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Título Window'])[1]/preceding::span[2]</value>
      <webElementGuid>df9fa1dc-fbab-4f51-b117-cbbfbc24f869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cascada Window'])[1]/preceding::span[6]</value>
      <webElementGuid>f119aa77-b7f4-4645-943a-87a497def05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inicio']/parent::*</value>
      <webElementGuid>9d4c7d8e-cfa4-4305-b222-521885a16fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>5110bbda-bad1-4c53-83a0-ebf5f71e846b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1017-btnInnerEl' and (text() = 'Inicio' or . = 'Inicio')]</value>
      <webElementGuid>82213349-0628-4a51-8c24-0c578633b0de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
