<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones (3)</name>
   <tag></tag>
   <elementGuidId>31b8c5f7-01e9-4dc0-bcea-edbacb192c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1141-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1141-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be714f01-627c-4794-b32e-211a6fbe49d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1141-btnInnerEl</value>
      <webElementGuid>699e82b0-7601-40ab-9e8d-7954acae7541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>3b46ce42-8b88-4261-b654-5aca7d5ae774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>ef1ce0ab-dc19-43b4-94fc-5bd69d6b495c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>8f13afac-4cb6-434d-af64-51b07dfecc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Opciones</value>
      <webElementGuid>063513bc-8c5c-4f2b-bcfb-f8b76e8ddf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1141-btnInnerEl&quot;)</value>
      <webElementGuid>ab849347-037c-4b57-a346-fa11d7126848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_NMREM_IFrame_1_2</value>
      <webElementGuid>5e3771a4-28fc-4d7d-8dda-520eecb15e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1141-btnInnerEl']</value>
      <webElementGuid>86501e7a-eae1-491f-a623-829b3bd6e3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1141-btnEl']/span[2]</value>
      <webElementGuid>34b0a400-721d-49cf-9492-65e5fc750082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[4]/following::span[7]</value>
      <webElementGuid>ea8f39d8-131a-4229-9b71-a0814e9e30fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[4]/following::span[8]</value>
      <webElementGuid>86d3b2b6-65c1-4d3f-90f6-3790460692ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREACION NUEVO REMATE 2 AUTOMATIZADO -NO ENTRAR-'])[2]/preceding::span[1]</value>
      <webElementGuid>976832e8-e167-48cc-9ee5-7675a998e192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganado'])[4]/preceding::span[1]</value>
      <webElementGuid>e3e8c7d9-c528-490a-be35-d6c931c5aea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td[2]/div/div/div/div/a/span/span/span[2]</value>
      <webElementGuid>f0168420-051a-4906-9e5d-5fd90ed2417e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1141-btnInnerEl' and (text() = 'Opciones' or . = 'Opciones')]</value>
      <webElementGuid>48cf1d94-31b3-49ee-91e4-cfdb249354e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
