<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grabar (2)</name>
   <tag></tag>
   <elementGuidId>3d719cb1-b78a-4926-9ee4-ae7350f4ff60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGuardar-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnGuardar-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>438e9c1c-a775-4390-92fd-0cd01387ce5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGuardar-btnInnerEl</value>
      <webElementGuid>75817e3e-5752-4043-b16b-03383745d4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>400e5b6e-c7fb-4163-bfbc-5b7cbc69f621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>e9cac42d-87ef-4d59-b74c-99ba6cfb763c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-success-small</value>
      <webElementGuid>ed15e2f1-6585-4dc7-934a-e06f2f54948c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grabar</value>
      <webElementGuid>56cee096-b609-4c1a-aac4-b9750b03579c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGuardar-btnInnerEl&quot;)</value>
      <webElementGuid>8127a8cd-e63e-470f-91f3-cf25ec79701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>1c6e41fe-3964-4c03-adc8-d4b086a771f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnGuardar-btnInnerEl']</value>
      <webElementGuid>9bab1a33-c0a0-4ea2-ac27-fc22a6f66477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='btnGuardar-btnEl']/span[2]</value>
      <webElementGuid>1b873603-2f49-4658-b70e-4fea91a20ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrar'])[1]/following::span[4]</value>
      <webElementGuid>03e833bd-4959-438c-b6ec-a365d6d4c6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[33]/following::span[8]</value>
      <webElementGuid>19fa9600-5f1c-4929-880a-3f9b50bb728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapa'])[1]/preceding::span[1]</value>
      <webElementGuid>fbacb077-80f1-48be-a642-a5e27a387658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lat/Lng:'])[1]/preceding::span[1]</value>
      <webElementGuid>cbd7d85c-8a1b-4e71-99af-6e0034896575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grabar']/parent::*</value>
      <webElementGuid>effb7af6-3174-41b0-bba1-1ec750a597ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a[2]/span/span/span[2]</value>
      <webElementGuid>e79f3aaf-2e0e-4bdf-beb0-79695e965ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnGuardar-btnInnerEl' and (text() = 'Grabar' or . = 'Grabar')]</value>
      <webElementGuid>94050e32-c6f4-4502-9cf9-9646883ae350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
