<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Imgenes Lote</name>
   <tag></tag>
   <elementGuidId>c440dc12-5bf5-4cac-bf85-d3bb8f3e640e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuitem-1133-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='menuitem-1133-textEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d4a6940-2074-4ca4-a3d2-f324431d61ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuitem-1133-textEl</value>
      <webElementGuid>7da7026f-b19a-4d08-81e1-3f4ba9e8de9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>efba53c8-5d27-4209-b7fd-ac529dedef6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-text x-menu-item-text-default x-menu-item-indent-no-separator</value>
      <webElementGuid>03933a25-4e59-4d5f-ba0b-709c6ba53612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a9e77db6-1d00-4875-b1fc-eea8728ced17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imágenes Lote</value>
      <webElementGuid>0351e883-f1ae-4e81-9249-1aeb0cae7cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuitem-1133-textEl&quot;)</value>
      <webElementGuid>3731b12c-9f09-4fa4-942d-ccc20920708e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2548_IFrame_1</value>
      <webElementGuid>04954397-f6e8-4d62-9fa0-6b7ed0c9a7b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menuitem-1133-textEl']</value>
      <webElementGuid>7f44f740-844f-44e6-b7f4-ea4552e1dc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuitem-1133-itemEl']/span</value>
      <webElementGuid>3326287b-c474-4adb-a46c-80502c00c92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar Lote'])[1]/following::span[1]</value>
      <webElementGuid>8d73a033-8200-4362-a0f8-72228d4e99ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Minor Version Upgrades Included!'])[1]/following::span[2]</value>
      <webElementGuid>bb2a67e1-7496-4234-b472-fc5377d31a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lotes con Derecho'])[1]/preceding::span[1]</value>
      <webElementGuid>256f5cb2-c535-48c2-b759-9e36c06c4532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar Lote'])[1]/preceding::span[2]</value>
      <webElementGuid>ba068e89-5126-4e4f-a198-7f482a86b302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imágenes Lote']/parent::*</value>
      <webElementGuid>290a91a0-edbe-4341-8704-f4a237686f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/span</value>
      <webElementGuid>b492c4c5-0dae-443d-af60-537247d75278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menuitem-1133-textEl' and (text() = 'Imágenes Lote' or . = 'Imágenes Lote')]</value>
      <webElementGuid>9acc7cd6-4bc7-4f13-9271-969463bc5c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
