<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones (2)</name>
   <tag></tag>
   <elementGuidId>0d9a26cf-0aae-4efa-a045-26af5781ca2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1130-btnWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1130-btnWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>59387df9-db5a-4154-b849-c8f7264c5d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1130-btnWrap</value>
      <webElementGuid>059b2f88-e39d-42f7-9620-8935f641caea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnWrap</value>
      <webElementGuid>708b4ee9-9568-4a8c-a7f6-4edc5e98355a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ec76f1a9-1dac-4959-910c-a3c1aa3b1812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>57664c38-cf28-4291-bb6c-32db440ff103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-wrap-default-toolbar-small x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>ae334d62-f389-468a-9549-e91beb24276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Opciones</value>
      <webElementGuid>b5786f55-3a3e-4332-8fff-7de180821a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1130-btnWrap&quot;)</value>
      <webElementGuid>e71081c5-5286-4038-ae3c-f5ca7e5efc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2554_IFrame</value>
      <webElementGuid>5522d9ee-7f7b-40c8-85c3-3eef5218fcde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1130-btnWrap']</value>
      <webElementGuid>8f0992b6-0349-49b3-b88f-f503e5b010d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1130']/span</value>
      <webElementGuid>6418ed86-e2e8-4394-b39b-995e0806eab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[2]/following::span[1]</value>
      <webElementGuid>0c79532e-8558-4fab-ad26-71a74e5869c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Lote'])[1]/following::span[5]</value>
      <webElementGuid>5eb4d87c-99a5-4f5b-a319-6850b98e711b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOTE 1'])[1]/preceding::span[4]</value>
      <webElementGuid>4e9aebc2-8f7e-4bb7-9d3b-e3ed2051f002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a/span</value>
      <webElementGuid>b86aec5b-e1a0-4c16-a41d-eeea586defdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1130-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>332057db-115d-46d5-a839-898763738873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
