<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones (5)</name>
   <tag></tag>
   <elementGuidId>ace443a7-4713-4e55-b9e6-b2b88eb3872c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1130-btnWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1130-btnWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5b5c8321-8a2c-4823-8aac-1ed8fb99cfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1130-btnWrap</value>
      <webElementGuid>64d30d87-deed-4a76-8ab2-d9020fe7b2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnWrap</value>
      <webElementGuid>f0f5d3e1-b7ed-4d46-8df6-8beaf9614bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>3529dc9a-f0a4-4542-8674-e41f07be85ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>51e47498-e55d-460a-b97b-a60c87ae2f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-wrap-default-toolbar-small x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>c5a9a93e-3c95-43af-bb21-33bd4a33fff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Opciones</value>
      <webElementGuid>4d9755ff-e23b-4d86-8ecc-fc16756ea8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1130-btnWrap&quot;)</value>
      <webElementGuid>b1f359b6-0d60-4652-82ae-482500b830f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2548_IFrame</value>
      <webElementGuid>16fbc36a-c71d-4931-81d2-a95a6dff6401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1130-btnWrap']</value>
      <webElementGuid>f37ca1b7-7a7c-4316-b9d2-ff1657a34a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1130']/span</value>
      <webElementGuid>9ca76911-5293-4b40-bd52-9a754be40404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[2]/following::span[1]</value>
      <webElementGuid>ba28ee14-a559-4e56-895f-1da64c842bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Lote'])[1]/following::span[5]</value>
      <webElementGuid>586f26a5-257d-410a-bf78-354bb3179959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BICICLETA'])[1]/preceding::span[4]</value>
      <webElementGuid>6bd237fd-e339-427f-891d-8bed558476ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a/span</value>
      <webElementGuid>0e344ab3-a9e1-459f-a901-c93816fa6c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1130-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>8d78e3c5-e1c6-4775-9760-e1b517822479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
