<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Carga Masiva Manual (1)</name>
   <tag></tag>
   <elementGuidId>8ccd2937-2239-4f4b-8ab5-36d532264223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnCargaMasiva-btnInnerEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnCargaMasiva-btnInnerEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6ee39568-1b5e-4079-adda-e204910d18f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCargaMasiva-btnInnerEl</value>
      <webElementGuid>9f7e8af0-52d5-4096-b76f-593f51a42f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>f1fa41f3-c0fb-4737-acdf-d43ecd224103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>34ae0acd-7deb-4aec-aa16-48f60f5e7c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-default-toolbar-small</value>
      <webElementGuid>7f8a40ea-39f7-4e1c-91b7-e51e5b85c86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carga Masiva Manual</value>
      <webElementGuid>d075625a-4f05-4c01-97fa-2fc2fa4d22f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnCargaMasiva-btnInnerEl&quot;)</value>
      <webElementGuid>f8dca633-6006-4681-8ef1-583917cca7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2556_IFrame</value>
      <webElementGuid>0056257b-77c5-486d-b201-89abe60e9c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnCargaMasiva-btnInnerEl']</value>
      <webElementGuid>6c7bd24f-1a08-4245-8801-0878ebc66b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='btnCargaMasiva-btnEl']/span[2]</value>
      <webElementGuid>4f4f99bb-10a8-44ca-b822-949fc4e08e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copiar'])[1]/following::span[4]</value>
      <webElementGuid>11eda687-ba1a-48dd-8b55-166fe202c44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar'])[1]/following::span[8]</value>
      <webElementGuid>1f96fbc8-52d6-48f9-a0d2-18d60d5a59fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carga Masiva 2'])[1]/preceding::span[2]</value>
      <webElementGuid>ad1636ea-cc03-4ba1-8f2f-1ec27b829a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carga Masiva Imagenes'])[1]/preceding::span[6]</value>
      <webElementGuid>32dfd42e-15e1-44e9-9b20-47045db78677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carga Masiva Manual']/parent::*</value>
      <webElementGuid>b5044096-f9ce-41f7-9944-0f8b83d8c3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span/span/span[2]</value>
      <webElementGuid>6390f932-ef67-4b5b-97e7-d4830b673e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnCargaMasiva-btnInnerEl' and (text() = 'Carga Masiva Manual' or . = 'Carga Masiva Manual')]</value>
      <webElementGuid>ef0e2dc4-4bab-4c3e-b8f9-fcaa56afda64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
