<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones</name>
   <tag></tag>
   <elementGuidId>59c6cd9e-6d1e-4184-83de-ff6c74a57073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1231-btnWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='2548']/parent::td/preceding-sibling::td[1]//span[contains(text(), 'Opciones')]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cc1562e9-07b0-4069-94ea-06150f11680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1231-btnWrap</value>
      <webElementGuid>db5352de-0582-447d-8066-3574b3ab8fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnWrap</value>
      <webElementGuid>a992f208-bcd2-4984-917e-6a2846715d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>7cba4164-04d3-4665-a6ee-8b86dd25cd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>8c2999f6-73cf-40f9-a83f-8168794186c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-wrap-default-toolbar-small x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>ca76ca2f-8106-4d92-ba66-691854739fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Opciones</value>
      <webElementGuid>c7177ac6-de94-4696-8a78-1a336e753602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1231-btnWrap&quot;)</value>
      <webElementGuid>d000ad7f-6754-4c2c-b827-07e99e427a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_NMREM_IFrame</value>
      <webElementGuid>1100d6c3-7959-41f9-9738-003c879c9916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1231-btnWrap']</value>
      <webElementGuid>ebde6bb0-26c0-4b90-9247-69fd86b07db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1231']/span</value>
      <webElementGuid>2a510b74-4699-45c5-8c8f-a70591536023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[6]/following::span[4]</value>
      <webElementGuid>86543057-8301-4370-8209-23af186d3a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[6]/following::span[5]</value>
      <webElementGuid>b8248b4c-819c-47ca-ad22-6bb5dc0feae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PNI GENÉRICA QA 3.0.2'])[1]/preceding::span[4]</value>
      <webElementGuid>71349174-298f-4495-a3bd-7cac36e8aa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[7]/tbody/tr/td[2]/div/div/div/div/a/span</value>
      <webElementGuid>bed4532f-af89-48d7-92fa-2cbe4ab81667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1231-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>f8aa8213-121d-41bf-82c9-c66ed924906c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1141-btnInnerEl']</value>
      <webElementGuid>b1e44570-caaa-482b-b655-909b49b76fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button-1141-btnEl']/span[2]</value>
      <webElementGuid>089da993-952c-4a9a-b052-5436423ff1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[4]/following::span[7]</value>
      <webElementGuid>7be64362-32c9-4d25-b5bb-15bc7f5b824a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[4]/following::span[8]</value>
      <webElementGuid>abe162be-c35b-4154-a0e8-addc40b6c66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREACION NUEVO REMATE 2 AUTOMATIZADO -NO ENTRAR-'])[2]/preceding::span[1]</value>
      <webElementGuid>c2b08993-bfde-476e-a842-c6b3ed34b551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganado'])[4]/preceding::span[1]</value>
      <webElementGuid>aa07caca-929f-4ad6-a05e-5de6f7184809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td[2]/div/div/div/div/a/span/span/span[2]</value>
      <webElementGuid>d93542af-18f9-4883-8d86-e8e53908f534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1141-btnInnerEl' and (text() = 'Opciones' or . = 'Opciones')]</value>
      <webElementGuid>e21c3f85-04ec-4f43-a6f2-40c86580101f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1141-btnWrap']</value>
      <webElementGuid>8c99aaa2-0c20-4e66-ba33-26ca2e6de1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1141']/span</value>
      <webElementGuid>ee4250f4-6628-4e0c-9ffc-5b624e3a3bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[4]/following::span[4]</value>
      <webElementGuid>41348354-3cdc-4430-a007-bf7b4135a06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[4]/following::span[5]</value>
      <webElementGuid>b451e969-6d9c-4c0b-86a7-a1ee1841a88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREACION NUEVO REMATE 2 AUTOMATIZADO -NO ENTRAR-'])[2]/preceding::span[4]</value>
      <webElementGuid>bd347ccb-601d-46b4-8c26-63cc79423354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td[2]/div/div/div/div/a/span</value>
      <webElementGuid>b7e10455-b051-4ce7-9bde-c4597f713a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1141-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>5e574a83-d451-4ee6-8590-473359dd68b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO PUBLICADO'])[1]/following::span[4]</value>
      <webElementGuid>c9032d8b-80de-49da-89e7-fd0a5fa13b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREACION NUEVO REMATE 2 AUTOMATIZADO -NO ENTRAR-'])[3]/preceding::span[4]</value>
      <webElementGuid>47658f6c-11ee-45db-8b94-e916a6238cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1288-btnWrap']</value>
      <webElementGuid>00865657-03a3-4d0d-885d-12fde6d45fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1288']/span</value>
      <webElementGuid>b18b9a6c-a249-4846-bf88-ae46270d449c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[9]/following::span[4]</value>
      <webElementGuid>6cd24ea5-e0a7-4c4e-9250-ec949fe7ace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[10]/following::span[5]</value>
      <webElementGuid>de0d33a1-3901-4a5b-a503-e54478695be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMATE PRUEBAS INFORME DECIMALES'])[1]/preceding::span[4]</value>
      <webElementGuid>0e7ea32a-538c-4566-b27f-123dae09e356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[12]/tbody/tr/td[2]/div/div/div/div/a/span</value>
      <webElementGuid>4e3f74bb-1e86-450f-a1bd-b7d24268849c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1288-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>0e1423b3-00db-4b7d-b96c-102d07a83d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1057-btnWrap']</value>
      <webElementGuid>b1979ad9-f7f0-4bc7-b64d-bba44a9a45ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1057']/span</value>
      <webElementGuid>fe4a83e1-6a47-411a-ba2c-9173d13d8cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lotes'])[1]/following::span[1]</value>
      <webElementGuid>de226496-aaf1-42c6-bde8-da7918c90cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redes'])[1]/following::span[4]</value>
      <webElementGuid>ce6d7a94-b117-4f20-9dc1-afb6ed6e73ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREACION NUEVO REMATE 2 AUTOMATIZADO -NO ENTRAR-'])[1]/preceding::span[4]</value>
      <webElementGuid>0ecff255-c8f7-4694-816b-bd75dafe70db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a/span</value>
      <webElementGuid>44af7eaf-c214-4103-b289-8c1c659a3d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1057-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>b899b5dd-37cc-40a4-b860-176c02572a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1078-btnWrap']</value>
      <webElementGuid>ac152dcd-04be-4fb5-b707-f2044a5b8ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1078']/span</value>
      <webElementGuid>e1721b75-6154-4381-9761-fd6f9912457a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUBLICADO'])[1]/following::span[4]</value>
      <webElementGuid>db50695e-aaab-45b9-b9ad-bb964f5bd467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[1]/following::span[5]</value>
      <webElementGuid>59c80e9d-52f1-4bd1-bd1d-10838fa12211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/div/div/div/div/a/span</value>
      <webElementGuid>1b9e2e8a-1b2d-463a-b819-a0d173b1a74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1078-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>41c2b1c5-0f79-4c08-a4e7-47e7dee9eca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1099-btnWrap']</value>
      <webElementGuid>6f7c59ee-58c6-41ab-935b-8c05e4392922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1099']/span</value>
      <webElementGuid>fc942640-15be-4dba-af66-7b62898c2a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[2]/following::span[5]</value>
      <webElementGuid>e83b6c49-9f84-4441-b5a9-380a5e038801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[2]/div/div/div/div/a/span</value>
      <webElementGuid>b834bf7b-f00d-464d-8703-c6c44bac04f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1099-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>1ec60061-266c-48a6-8b15-d8e255cef9a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
