<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grabar (1)</name>
   <tag></tag>
   <elementGuidId>cc7dc4cc-c19c-47db-901c-350daf1ff1aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnGuardar-btnEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnGuardar-btnEl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee3c48cc-6033-4c14-9267-4f8185b18c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnGuardar-btnEl</value>
      <webElementGuid>48920149-6f73-43c2-aa7e-b814a29cdb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnEl</value>
      <webElementGuid>f02c2878-acd2-426f-af32-af6eec2d10e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9c597c5d-0358-4a0c-bfb0-1aa5e1997885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d0f0b4d3-d7b0-408b-9b1d-1e9b39a123aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-button x-btn-button-success-small x-btn-text  x-btn-icon x-btn-icon-left x-btn-button-center </value>
      <webElementGuid>925ef16d-ec9f-445e-aed3-f429b28a5fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Grabar</value>
      <webElementGuid>b860f84c-d038-4073-bb05-360825b25d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnGuardar-btnEl&quot;)</value>
      <webElementGuid>f5eb84bd-15db-4ccb-a10f-d1964ab634ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe</value>
      <webElementGuid>d8fdf9e9-3f4e-4d1e-943a-b02e907e3e48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnGuardar-btnEl']</value>
      <webElementGuid>f6eae2b2-4f75-4328-97d1-94e7b53679e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='btnGuardar-btnWrap']/span</value>
      <webElementGuid>11423874-a233-4c97-9b29-52ffb46ac1ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Borrar'])[1]/following::span[2]</value>
      <webElementGuid>18cb2a08-3aad-4a3b-95e2-3b75e58b60d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[33]/following::span[6]</value>
      <webElementGuid>ee764abc-b3b6-484e-b384-ea01f13c6c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mapa'])[1]/preceding::span[3]</value>
      <webElementGuid>51d99ec3-c9eb-4e00-99e3-0e543069063c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a[2]/span/span</value>
      <webElementGuid>9a7c6d41-2958-4682-bb93-eb92c21e09e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnGuardar-btnEl' and (text() = ' Grabar' or . = ' Grabar')]</value>
      <webElementGuid>f00ca46a-5e3b-4fea-aa82-9d8c1a369a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
