<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones (1)</name>
   <tag></tag>
   <elementGuidId>35676a7c-85a1-4521-a45d-7f27c7065a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1120-btnWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1120-btnWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c99bb2db-f479-45b8-b0f9-3e2e9d1673c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1120-btnWrap</value>
      <webElementGuid>7b85a7f8-7114-4d1b-b388-5ec62a089f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnWrap</value>
      <webElementGuid>7e78249b-b2b3-4277-88cf-71d0dc6a1c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1e412aae-1442-4be3-b6b6-ba5b380a2ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1706f744-d4ad-4af9-ab1d-114dfa0b24c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-wrap-default-toolbar-small x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>9923e079-8b66-49da-b076-c0488ea59e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Opciones</value>
      <webElementGuid>b7d61cfd-2526-4876-8d1d-357bf68d4e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1120-btnWrap&quot;)</value>
      <webElementGuid>10ed5142-09c2-420e-9057-cfb4f0da7cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_NMREM_IFrame_1</value>
      <webElementGuid>2e920953-957a-44bc-87cd-a9bc7b31ccf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1120-btnWrap']</value>
      <webElementGuid>d0d9ee85-ff39-4896-83b9-cd96a214a093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1120']/span</value>
      <webElementGuid>6fd81ea0-3edf-4d59-8405-dd8d9ae977e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO PUBLICADO'])[2]/following::span[4]</value>
      <webElementGuid>b972cb98-e829-461e-8b1c-c04b6f660295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mixto'])[3]/following::span[5]</value>
      <webElementGuid>0f550f26-9abe-4ade-9313-6992c823e43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREACION NUEVO REMATE 2 AUTOMATIZADO -NO ENTRAR-'])[2]/preceding::span[4]</value>
      <webElementGuid>ca33672a-00c4-4177-a1da-b44872560456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td[2]/div/div/div/div/a/span</value>
      <webElementGuid>f36dbaee-8346-46dc-9849-bc47efb62b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1120-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>33042528-93a8-4363-98e8-c49f5224ac18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
