<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Opciones (4)</name>
   <tag></tag>
   <elementGuidId>69dbe390-ec29-490c-9632-c259d4a58068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-1130-btnWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button-1130-btnWrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9926096-c20a-46f3-9a3d-a486246fe535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-1130-btnWrap</value>
      <webElementGuid>80f61d19-bdb1-466c-839b-4da863e12743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnWrap</value>
      <webElementGuid>298444af-b453-4433-aeb6-2c156a442748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>4c2aa1a5-48de-4815-8fa1-f49a020d9d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f63717b6-215d-433b-88ee-3e248766b882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-wrap x-btn-wrap-default-toolbar-small x-btn-arrow x-btn-arrow-right</value>
      <webElementGuid>11bee957-f293-4b2c-a8fd-cc49a4ca1797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Opciones</value>
      <webElementGuid>4769f92a-ccac-4217-8ea2-76f39946b0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-1130-btnWrap&quot;)</value>
      <webElementGuid>ca3608ad-7b14-4eec-9e3d-bc00de110c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Nmina Remates_WIN_Lotes2555_IFrame_1</value>
      <webElementGuid>8a829f2e-10d2-486e-96d3-1a20ec38ce0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button-1130-btnWrap']</value>
      <webElementGuid>35e5518a-1abd-4883-89d5-4a2efac4ba26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='button-1130']/span</value>
      <webElementGuid>a6e4ec96-bca1-48d2-b7be-5afd6fbc006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[2]/following::span[1]</value>
      <webElementGuid>0a29b32a-d846-4d97-8d3f-0498b0768dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Lote'])[1]/following::span[5]</value>
      <webElementGuid>af8e2e41-f599-40c4-a154-805b284787e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lote 1'])[1]/preceding::span[4]</value>
      <webElementGuid>8fb7862c-4f32-4fdf-b277-0fb06b4e35ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div/a/span</value>
      <webElementGuid>aaa94616-99b6-49c6-9ca8-7bfb58d229eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'button-1130-btnWrap' and (text() = ' Opciones' or . = ' Opciones')]</value>
      <webElementGuid>f3625a38-19e1-4b4f-8731-be8b548b8201</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
