<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Guardar Lotes</name>
   <tag></tag>
   <elementGuidId>4f7b5c10-4c16-4840-8574-fe3b76f744dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnSaveExcel-btnInnerEl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSaveExcel-btnInnerEl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>521bac85-bbcb-4afc-bd0b-1e96da350b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveExcel-btnInnerEl</value>
      <webElementGuid>9a6b56ec-c67a-4cde-a452-d83fca385086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>btnInnerEl</value>
      <webElementGuid>25c84407-c92c-40ac-8d9b-e235d7edc4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a6223a05-5e51-43bd-a794-37e21d8e3995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-btn-inner x-btn-inner-success-small</value>
      <webElementGuid>8ec993ab-7fe4-4659-b3a4-bc62f0e972d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar Lotes</value>
      <webElementGuid>2b8a6b5e-3a74-4cac-8268-00b11ff44d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveExcel-btnInnerEl&quot;)</value>
      <webElementGuid>0141b358-690f-4183-80f0-ed1ac4c2f5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Administrador/iframe_Carga Masiva_ext-element-57</value>
      <webElementGuid>21008842-b436-4708-9b04-987532b5c1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnSaveExcel-btnInnerEl']</value>
      <webElementGuid>d10a8f85-c628-4e9a-87f8-4135a8bbabe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='btnSaveExcel-btnEl']/span[2]</value>
      <webElementGuid>2cdece50-faf6-4e5b-a5c6-3079559f9783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre Lote'])[1]/following::span[4]</value>
      <webElementGuid>e7367d77-ee07-4419-923f-8678037344d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sobreescribir Lote'])[1]/following::span[7]</value>
      <webElementGuid>f9292389-3474-40f2-b129-d4f25f6edaba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planilla Excel'])[1]/preceding::span[2]</value>
      <webElementGuid>6235e572-128f-44c3-a404-0163cb1b3107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Guardar Lotes']/parent::*</value>
      <webElementGuid>313dbc3d-c50d-4978-af05-4f1c995732bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/span/span/span[2]</value>
      <webElementGuid>e71a429e-4e47-4508-9db9-2af650f06e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnSaveExcel-btnInnerEl' and (text() = 'Guardar Lotes' or . = 'Guardar Lotes')]</value>
      <webElementGuid>83037307-be2a-40a3-a8e8-c79a639c1f86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
