<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Registrar</name>
   <tag></tag>
   <elementGuidId>af7445a8-cda9-4ee9-b020-a4434e6ab32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button_registrar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button_registrar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc0aace2-a24b-4f97-acff-c5d1886cc952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button_registrar</value>
      <webElementGuid>319b3535-4b29-4233-bbac-eba16c457c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f1ba24b8-3f09-4d74-8d3b-3cb0a10bc5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-lg</value>
      <webElementGuid>788b2199-3467-4f79-97d2-f6820952050d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>btnRegistroClick()</value>
      <webElementGuid>7c06a093-c6bc-40ff-a083-8df56ca4186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>!remate.aplicaEncuesta || (remate.aplicaEncuesta &amp;&amp; encuestaCompletada)</value>
      <webElementGuid>9f383d62-9b69-42ad-b0ef-02a884a2dd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!inscripcion.aceptoCondiciones || rutExiste || frmGarantia.$invalid || (muestraCuentasBancarias == 1 &amp;&amp; !tieneCuentasBancarias)</value>
      <webElementGuid>7f10a549-5509-4a79-b082-19f1539b5bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gtag('event', 'Fin de la solicitud', { 'event_category': 'Trámite digital', 'event_label': 'Trámite - 1100130007'});</value>
      <webElementGuid>a6eeb88a-79d2-466d-9264-a68411df3ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Registrar
                            </value>
      <webElementGuid>29608bdf-df98-4125-a769-a37c0e5f6eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button_registrar&quot;)</value>
      <webElementGuid>7dc76b8a-f12d-4e4f-9657-3bc6e9ff253f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button_registrar']</value>
      <webElementGuid>af2063b9-b61e-4ca1-bf4f-2b3693264630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[14]/div/div/button</value>
      <webElementGuid>92772b8b-2be7-4158-a4ee-4aad257bbcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Politicas de Privacidad'])[1]/following::button[1]</value>
      <webElementGuid>5cc6588d-3c45-42f3-861e-bb080e941667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bases Especiales'])[1]/following::button[1]</value>
      <webElementGuid>e23728fe-8990-4530-917a-7ba24fb8c6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continuar'])[1]/preceding::button[1]</value>
      <webElementGuid>cdc1445a-e0f7-4b0d-ae53-b57e196e4cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volver'])[1]/preceding::button[2]</value>
      <webElementGuid>170d66d4-71ac-4e0e-8f27-e6cd00a4a12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registrar']/parent::*</value>
      <webElementGuid>1a6f0b10-95df-425c-9e84-c35145d65386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>bf38bffa-d447-4fe9-83ee-c7f79f423ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button_registrar' and @type = 'submit' and (text() = '
                                Registrar
                            ' or . = '
                                Registrar
                            ')]</value>
      <webElementGuid>484f3b37-0a07-4c80-9be5-e04aba23e7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
