<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Politicas de Privacidad_a-6e4s85e5w5x</name>
   <tag></tag>
   <elementGuidId>9d623a56-4071-4bc9-9410-a41994c93b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6e4s85e5w5x']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6e4s85e5w5x&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>37f09dac-feaa-45a5-a7eb-aea06a155e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>8fe958ef-54ae-434a-bfab-28a4d9de4203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>3bc6f9d2-f4e2-4b09-872b-ab351642a72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>551d27b3-abc7-4921-88d4-63f41f945045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>eaf70876-7920-487e-adbe-b879f495de9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6e4s85e5w5x</value>
      <webElementGuid>0185faf0-bca7-4576-b679-27d8b77138c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47bcda64-1369-42a6-8430-c53f7a920c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>61b71f47-e530-4e54-b820-7b4b46566d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>eb463619-3e7b-42e6-9fc7-ecf1ff644406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcmzTYfAAAAAMQSzwumkMkT_oT31hpXhESvOcEj&amp;co=aHR0cHM6Ly9xYXBsZy5wbGF0YWZvcm1hZ3JvdXAuY2w6NDQz&amp;hl=es-419&amp;v=zIriijn3uj5Vpknvt_LnfNbF&amp;size=normal&amp;cb=krmo3stirh9f</value>
      <webElementGuid>7395efeb-4fa4-4b09-a9fb-e7b6729d9d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_body&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal ng-valid-maxlength ng-valid-pattern ng-dirty ng-valid-parse ng-valid-rut ng-valid-email ng-valid ng-valid-required&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>fda1850e-b74b-45a7-967a-a37fd648e258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6e4s85e5w5x']</value>
      <webElementGuid>a337be58-3175-4c5c-a063-0c5a5ab5ddc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[13]/div/div/div/div/div/iframe</value>
      <webElementGuid>fb9e3aa1-28dc-4998-b3b9-780f57840821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>463ba2f1-e87e-4da7-a58f-81d696bbc4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-6e4s85e5w5x' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcmzTYfAAAAAMQSzwumkMkT_oT31hpXhESvOcEj&amp;co=aHR0cHM6Ly9xYXBsZy5wbGF0YWZvcm1hZ3JvdXAuY2w6NDQz&amp;hl=es-419&amp;v=zIriijn3uj5Vpknvt_LnfNbF&amp;size=normal&amp;cb=krmo3stirh9f']</value>
      <webElementGuid>adf12228-8c31-43e1-bdba-deda1a0b2c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
