<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CUIT_rut</name>
   <tag></tag>
   <elementGuidId>8f5d1f5a-02f3-4764-a17f-68d7dbd4c2c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_rut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_rut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b72a2719-2590-40c4-a18c-f025a1a4403c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9167c541-4cb8-46f5-a3cc-240aa92baf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>inscripcion.pais.FnValidacionDocumentoPersona === 'ValidarCuit'</value>
      <webElementGuid>8f80a885-94aa-4f44-b0f6-21546f888215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cuit-format</name>
      <type>Main</type>
      <value>live</value>
      <webElementGuid>18666a40-71fc-4700-a28b-cf0fc85e4817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-scope ng-valid-rut ng-empty ng-invalid ng-invalid-required ng-valid-maxlength input-invalid</value>
      <webElementGuid>5d556a1d-cee3-400f-b9be-753b968a836a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>72f7e567-3555-4c8d-9046-e659197007f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>20-12345678-0</value>
      <webElementGuid>852452e0-9bc3-4ac4-a94b-8e588e07983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rut</value>
      <webElementGuid>2f3c56e0-6d97-4c7b-a47a-d5a34a1f51af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_rut</value>
      <webElementGuid>ca9d8f13-db82-44fd-9466-824826fdbdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inscripcion.rut</value>
      <webElementGuid>a9dc285f-777e-40cc-a194-f949d578e7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ValidarRut();</value>
      <webElementGuid>c3fe0fcd-9355-4cb1-a187-55af4f68760e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>inscripcion.pais.FnValidacionDocumentoPersona === 'ValidarCuit' ? true : false</value>
      <webElementGuid>0577c321-2dc8-48aa-9eb1-5232d931caa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>bloquearcampos</value>
      <webElementGuid>b490d0c1-d72f-4adc-b1a5-03610786ce41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'input-invalid': (frmGarantia.rut.$pristine || (frmGarantia.rut.$error.required &amp;&amp; frmGarantia.rut.$touched)) }</value>
      <webElementGuid>64df8db5-d7c5-4b99-8b1c-514361959e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6add5a10-b5eb-4c01-af16-c9289013e6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_rut&quot;)</value>
      <webElementGuid>80faa9c0-5a56-475b-bbef-ab1bc34eb566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_rut']</value>
      <webElementGuid>aa5c772e-9ff5-4f61-b438-97b2bcb816e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[4]/div/input</value>
      <webElementGuid>071f92ed-d01a-4e70-a0c9-8d7faba3ac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>fd67b528-3923-4974-bfff-0ad398e4ec69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '20-12345678-0' and @name = 'rut' and @id = 'txt_rut']</value>
      <webElementGuid>ec46952b-b4e2-4ea2-a926-43daf0bf1f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
