<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellido Paterno_paterno</name>
   <tag></tag>
   <elementGuidId>e52f8cb1-b3e9-42d8-a731-feb5c3cfbd9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_apepat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_apepat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2299d16c-6822-47bf-9864-f637d9610b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02d2f416-37b4-44b8-b37a-c8063ab9d83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>3272dff5-4c0d-467b-a2f1-d9fa3c06e09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_apepat</value>
      <webElementGuid>e5c83ce9-3421-4555-8456-88fd2c6ad57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inscripcion.paterno</value>
      <webElementGuid>3377eb1f-f0ce-4ef6-b000-059e49a07cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>463dc23a-d975-49b1-ae9b-4fc439574c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(inscripcion.esPersona == 'false' || bloquearcampos )</value>
      <webElementGuid>2c45a084-6519-49da-aee7-191d53c787fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paterno</value>
      <webElementGuid>6d01e6f0-47ba-4445-ba69-f3707d8750d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>inscripcion.esPersona=='true'</value>
      <webElementGuid>becaed9e-2f1d-40bb-8e75-deb3c53a777c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'input-invalid': ((frmGarantia.paterno.$pristine &amp;&amp; inscripcion.esPersona == 'true') || (frmGarantia.paterno.$error.required &amp;&amp; frmGarantia.paterno.$touched)), '': inscripcion.esPersona == 'false' }</value>
      <webElementGuid>13b8c9c3-fa57-4f1c-a0a3-27e57510c83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b2c76de5-a694-4326-960f-21822931dcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_apepat&quot;)</value>
      <webElementGuid>7cf0d832-2e95-4ef5-bf5f-6403640064de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_apepat']</value>
      <webElementGuid>027bf31b-c7ed-4e20-bdfc-b450d0a4fb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[5]/div/input</value>
      <webElementGuid>4688cd56-73a5-4c62-aa5f-d989d5b75e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>a2d9cc7d-17fd-4206-b0d8-20d0487ca00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_apepat' and @name = 'paterno']</value>
      <webElementGuid>3b84b3e9-dc35-4c30-b8cd-359b725e54f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
