<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellido Materno_materno</name>
   <tag></tag>
   <elementGuidId>296dc4be-894a-499a-8983-1b07be8db2ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_apemat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_apemat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e36f93e6-7a90-4eac-be93-746f33940c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7b092ee5-6a62-4682-bc2c-34ddbd2f9398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required</value>
      <webElementGuid>f2684b2a-fca8-4e9a-99bc-36bed4675e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_apemat</value>
      <webElementGuid>c36f5a2a-349a-4359-919d-00548bbbbd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inscripcion.materno</value>
      <webElementGuid>8309aee4-fa61-4c72-b8be-db1ee01b36db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8d67277c-f212-4eca-9f34-5b49fa407736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>(inscripcion.esPersona == 'false' || bloquearcampos )</value>
      <webElementGuid>b915de6b-5b62-4512-88d1-7675a384dd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>materno</value>
      <webElementGuid>352ac88d-6e49-458e-b29e-7f678eb8f91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>inscripcion.esPersona=='true'</value>
      <webElementGuid>31b5f85c-ba9e-4aef-bd0c-3878da8a8894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'input-invalid': ((frmGarantia.materno.$pristine &amp;&amp; inscripcion.esPersona == 'true') || (frmGarantia.materno.$error.required &amp;&amp; frmGarantia.materno.$touched)), '': inscripcion.esPersona == 'false' }</value>
      <webElementGuid>4a4d24e8-6be8-41e9-9c7b-660857822822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ad5703a7-9077-4903-a889-2bf29c8e0f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_apemat&quot;)</value>
      <webElementGuid>f17a773e-86ec-41c9-a474-abaff9eae33b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_apemat']</value>
      <webElementGuid>d286a8d0-17dc-4b4a-b83c-d9d3160a1677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[5]/div[2]/input</value>
      <webElementGuid>dd9ac6ee-4502-486c-ad8c-884791cc2674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>01a5239e-df87-4e16-a1eb-63baaeb9649d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txt_apemat' and @name = 'materno']</value>
      <webElementGuid>ee4372fb-acd4-4170-97bf-0031eacaf156</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
