<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clave_clave</name>
   <tag></tag>
   <elementGuidId>35402938-302e-460e-91bc-87c0963d1d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_clave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_clave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>47c6adb4-c259-4bb6-9d18-8e92995dbc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d6ddbc11-66bc-4fdc-8057-ca05773064c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>af69704b-80f8-45cf-97eb-290ca3aae2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_clave</value>
      <webElementGuid>8e9f193b-72cb-4f1d-a590-5e9622d8f75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inscripcion.clave</value>
      <webElementGuid>805f0fa3-afd3-4605-91f1-ca83cca848a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>clave</value>
      <webElementGuid>be698566-a815-407a-adb8-9ca22e199a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'input-invalid': (frmGarantia.clave.$pristine  || (frmGarantia.clave.$error.required &amp;&amp; frmGarantia.clave.$touched)) }</value>
      <webElementGuid>cf131433-30fc-4e90-8340-2a0875d9eb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_clave&quot;)</value>
      <webElementGuid>50610903-0940-4f45-8e00-f649fd665598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_clave']</value>
      <webElementGuid>8fd9806b-e531-4011-b460-a1645121942a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[9]/div/input</value>
      <webElementGuid>48b6724c-1ace-4ea9-84fc-b7d736d2f65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>d728fc76-4105-42d1-afb0-c62b6fa961e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'txt_clave' and @name = 'clave']</value>
      <webElementGuid>8501960b-9d1f-4fec-adc4-59d4ed0f6d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
