<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Repite Clave_repiteClave</name>
   <tag></tag>
   <elementGuidId>3bc96c5c-e70b-4491-8408-0820536b8e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_repite_clave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_repite_clave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b72ecf4-84fe-4ca2-a2c9-18b45ae81258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4c1aef7a-7f7a-43b3-b730-7749aebf5048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>1630f1b5-7142-406b-8836-c95c607ce516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_repite_clave</value>
      <webElementGuid>fc80488b-205e-4329-9381-011cad4db8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inscripcion.repiteClave</value>
      <webElementGuid>62d95def-7b11-4dcd-a59a-36d90f9d29b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repiteClave</value>
      <webElementGuid>fb43588f-998b-4b79-b055-e99158ab42d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'input-invalid': (frmGarantia.repiteClave.$pristine  || (frmGarantia.repiteClave.$error.required &amp;&amp; frmGarantia.repiteClave.$touched)) }</value>
      <webElementGuid>7b58aa20-26e3-4fb3-bad2-9fa92163fd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_repite_clave&quot;)</value>
      <webElementGuid>e566196c-de5f-4de1-a935-69d1f7f4e078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_repite_clave']</value>
      <webElementGuid>dbaf30eb-126c-4930-a8d1-c9c032cd300a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[9]/div[2]/input</value>
      <webElementGuid>32f92b0f-1f82-4ef7-9255-54b587674897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>48b7345c-6ec3-437e-b580-465c5ffd668a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'txt_repite_clave' and @name = 'repiteClave']</value>
      <webElementGuid>8aaba007-dbcc-49f1-9468-aebff220912d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
