<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CATAMARCACRDOBACORRIENTESCIUDAD AUTN_f206ec</name>
   <tag></tag>
   <elementGuidId>d9017d4d-04b2-4bf3-88d5-89872e3fe599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Sel_regionidentidad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Sel_regionidentidad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>df4a5c4e-5155-4805-831e-c0ccd42c63b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched input-invalid ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>433e5ff3-724b-4330-9af5-94a76bc1d2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Sel_regionidentidad</value>
      <webElementGuid>0d3d0ab8-2fbc-4a4a-bb83-c122fea4766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>658413a1-64f6-4a77-9f9c-56a8f434aa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>82e2e3b0-bd1a-4cfd-af1f-5c4518a3295a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>option.descripcion for option in regiones track by option.id</value>
      <webElementGuid>cd6b1982-abb7-48db-bb12-911073be5f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>inscripcion.region</value>
      <webElementGuid>b44c5313-4d60-4622-9a71-2fd336c1beb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ObtenerComunas(inscripcion.region)</value>
      <webElementGuid>a0214ad9-daa0-4310-a960-067ebe475c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ 'input-invalid': (frmGarantia.region.$pristine  || (frmGarantia.region.$error.required &amp;&amp; frmGarantia.region.$touched)) }</value>
      <webElementGuid>019a19d3-6cab-4c29-8857-190c627447eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1b116933-7bed-4db4-9cfc-b32e09c0acbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CATAMARCACÓRDOBACORRIENTESCIUDAD AUTÓNOMA DE BUENOS AIRESCHACOCHUBUTENTRE RÍOSFORMOSAJUJUYLA PAMPALA RIOJAMENDOZAMISIONESNEUQUÉNBUENOS AIRESRÍO NEGROSALTASAN JUANSAN LUISSANTA CRUZSANTA FESANTIAGO DEL ESTEROTUCUMÁNMAULEEXTRANJERO</value>
      <webElementGuid>eecadcff-dea9-4980-86de-1357210242bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Sel_regionidentidad&quot;)</value>
      <webElementGuid>b138ee71-db8b-4e38-b53d-d017d757574c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Sel_regionidentidad']</value>
      <webElementGuid>88cefd45-88b7-420f-a71f-3c4087e2fc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='id_body']/div/div[2]/div/div/form/div[7]/div/select</value>
      <webElementGuid>8143703f-1fdb-463d-9a4a-bae0a97ac117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provincia'])[1]/following::select[1]</value>
      <webElementGuid>b055da01-a8bf-481b-8702-eb447c313276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Región'])[1]/following::select[1]</value>
      <webElementGuid>bb7453f7-d530-4ef1-b8f6-77c043374e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comuna'])[1]/preceding::select[1]</value>
      <webElementGuid>b943df9e-9b9e-4aca-ae3d-5f76603326e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localidad'])[1]/preceding::select[1]</value>
      <webElementGuid>e344cd09-2844-41e3-9095-3876cecd12fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>caf576a5-093e-47d2-8826-30ee4238cab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Sel_regionidentidad' and @name = 'region' and (text() = 'CATAMARCACÓRDOBACORRIENTESCIUDAD AUTÓNOMA DE BUENOS AIRESCHACOCHUBUTENTRE RÍOSFORMOSAJUJUYLA PAMPALA RIOJAMENDOZAMISIONESNEUQUÉNBUENOS AIRESRÍO NEGROSALTASAN JUANSAN LUISSANTA CRUZSANTA FESANTIAGO DEL ESTEROTUCUMÁNMAULEEXTRANJERO' or . = 'CATAMARCACÓRDOBACORRIENTESCIUDAD AUTÓNOMA DE BUENOS AIRESCHACOCHUBUTENTRE RÍOSFORMOSAJUJUYLA PAMPALA RIOJAMENDOZAMISIONESNEUQUÉNBUENOS AIRESRÍO NEGROSALTASAN JUANSAN LUISSANTA CRUZSANTA FESANTIAGO DEL ESTEROTUCUMÁNMAULEEXTRANJERO')]</value>
      <webElementGuid>3c97e664-60d8-4cff-bc52-05110f011c8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
